object FundoTransparente: TFundoTransparente
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 127
  BorderStyle = bsNone
  Caption = 'FundoSemiTransparente'
  ClientHeight = 240
  ClientWidth = 463
  Color = clGrayText
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
end
