program WR2;

  ///////////////////////////////////////////// DOCUMENTAÇÃO ///////////////////////////////////////////////////////////
  ///  SEÇÃO 1: UntiFunções - todos *.pas SEM form (dfm)
  ///  SEÇÃO 2: DataModules - Banco de Dados e Banco de Imagens
  ///  SEÇÃO 3: TCAD - CADASTRO MESTRE
  ///  SEÇÃO 4: TCON
  ///  SEÇÃO 5: TIMPRMESTRE - Relatórios do QuickReports
  ///  SEÇÃO 6: Configurações -
  ///  SEÇÃO 7: Telas de aviso ou Aguarde -
  ///  SEÇÃO 8: TFrame -
  ///  SEÇÃO 9: Financeiro - Não Mecher nessas Telas
  ///  SEÇÃO 10: Agenda - Fica Responssável aqui toda a parte de CRM (Relacioamento com o Cliente email, e historico de atendimentos)
  ///  SEÇÃO 11: Telas não padronizadas - Todas tela não padrão gera treinamento e deve ser extinta (Penssar bastante em como padronizar)

  ///////////////////////////////////////////// FIM DOCUMENTAÇÃO ///////////////////////////////////////////////////////
{
  Copiar o exe para um com a versão no nome
  PostBuild Events
  copy /B "$(OutputPath)" "$(OutputDir)$(OutputName) $(VerInfo_MajorVer).$(VerInfo_MinorVer).$(VerInfo_Release).$(VerInfo_Build)$(OutputExt)"
}

{$R *.dres}

uses
  ShareMem,
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,
  MidasLib,
  Forms,
  System.SysUtils,
  Winapi.Windows,
  IniFiles,
  ImpTexto in '..\Componentes\ImpTexto.pas',
  uAcessoRemoto in 'uAcessoRemoto.pas',
  wrForms in '..\Geral\wrForms.pas',
  uControleWR in '..\Geral\uControleWR.pas',
  uCriptografia in '..\Geral\uCriptografia.pas',
  uEmail in '..\Geral\uEmail.pas',
  uEmailMassa in 'uEmailMassa.pas',
  uExportarImportarGrupoProdutoExcel in '..\Geral\uExportarImportarGrupoProdutoExcel.pas',
  Utils.Financeiro in 'app\Utils\Utils.Financeiro.pas',
  uGerenciadorThreads in 'uGerenciadorThreads.pas',
  uGridLayoutView in '..\Geral\uGridLayoutView.pas',
  uLayout in '..\Geral\uLayout.pas',
  Classes.APP in 'app\Classes\Classes.APP.pas',
  uOFXReader in '..\Geral\uOFXReader.pas',
  uPCInfo in '..\Geral\uPCInfo.pas',
  uParametrosExecutavel in '..\Geral\uParametrosExecutavel.pas',
  Utils.PlanoContas in 'app\Utils\Utils.PlanoContas.pas',
  uRegistro in 'uRegistro.pas',
  uResultadoExercicio in '..\Geral\Contas\uResultadoExercicio.pas',
  uWeb in '..\Geral\uWeb.pas',
  uXmlToHtml in '..\Geral\uXmlToHtml.pas',
  Classes.WR in 'app\Classes\Classes.WR.pas',
  wrConstantes in 'wrConstantes.pas',
  wrConversao in 'wrConversao.pas',
  wrFormataCampo in 'wrFormataCampo.pas',
  wrFuncoes in '..\Geral\wrFuncoes.pas',
  wrIntegracaoIBASI in 'wrIntegracaoIBASI.pas',
  wrIntegracaoTEC in 'wrIntegracaoTEC.pas',
  wrPreencheLookup in 'wrPreencheLookup.pas',
  Rotinas in 'Rotinas.pas',
  UnitFuncoes in '..\Geral\UnitFuncoes.pas',
  uWRCalculaConfiguracoes in '..\Componentes\uWRCalculaConfiguracoes.pas',
  uSCConsultaCNPJ in '..\Componentes\CnpjReceita\Fontes\uSCConsultaCNPJ.pas' {FSCConsultaCNPJ},
  cxSchedulerEventEditor in '..\Componentes\DevExpress\ExpressScheduler\Sources\cxSchedulerEventEditor.pas' {cxSchedulerEventEditorForm},
  DataModuleBanco in '..\Geral\DataModuleBanco.pas' {DMBanco: TDataModule},
  DataModuleFrxDataSets in '..\Geral\DataModuleFrxDataSets.pas' {DMFrxDatasets: TDataModule},
  DataModule in 'DataModule.pas' {DM: TDataModule},
  DataModuleBackup in '..\Geral\DataModuleBackup.pas' {DMBackup: TDataModule},
  DataModuleAtualizacao in 'DataModuleAtualizacao.pas' {DMAtualizacao: TDataModule},
  DataModuleCadastrosClient in '..\Geral\DataModuleCadastrosClient.pas' {DMCadastrosClient: TDataModule},
  DataModuleRegistro in 'DataModuleRegistro.pas' {DMRegistro: TDataModule},
  DataModuleBoletos in '..\Geral\DataModuleBoletos.pas' {DMBoletos: TDataModule},
  DataModuleImpressao in '..\Geral\DataModuleImpressao.pas' {DMImpressao: TDataModule},
  DataModuleBigData in '..\Geral\DataModuleBigData.pas' {DMBigData: TDataModule},
  DataModuleEdits in '..\Geral\DataModuleEdits.pas' {DMEdits: TDataModule},
  DataModuleSat in 'DataModuleSat.pas' {DMSat: TDataModule},
  uDMRelatorios in 'uDMRelatorios.pas' {DMRelatorios: TDataModule},
  CadMestre in '..\Geral\CadMestre.pas' {FrmCadMestre},
  Cad in '..\Geral\Cad.pas' {FrmCad},
  ConMestre in '..\Geral\ConMestre.pas' {ConsuMestre},
  Consulta in 'Consulta.pas' {FrmConsulta},
  ImpMestre in '..\Geral\ImpMestre.pas' {ImpriMestre},
  ImpFinanceiro_Caixa in '..\Geral\Contas\ImpFinanceiro_Caixa.pas' {ImpriFinanceiro_Caixa},
  ImpFaturamento in 'ImpFaturamento.pas' {ImpriFaturamento},
  ImpVendaA4 in 'ImpVendaA4.pas' {ImpriVendaA4},
  ImpDuplicata in '..\Geral\Contas\ImpDuplicata.pas' {ImpriDuplicata},
  ImpCarne in '..\Geral\Contas\ImpCarne.pas' {ImpriCarne},
  ImpVenda in 'ImpVenda.pas' {ImpriVenda},
  ImpProdutos_Gerencial in 'ImpProdutos_Gerencial.pas' {ImpriProdutos_Gerencial},
  ImpFinanceiro in '..\Geral\Contas\ImpFinanceiro.pas' {ImpriFinanceiro},
  ImpMovimento_Estoque in '..\Geral\ImpMovimento_Estoque.pas' {ImpriMovimento_Estoque},
  ImpVeiculos in 'ImpVeiculos.pas' {ImpriVeiculos},
  ImpVeiculos_Estoque in 'ImpVeiculos_Estoque.pas' {ImpriVeiculos_Estoque},
  ImpVendas_Periodo in 'ImpVendas_Periodo.pas' {ImpriVendas_Periodo},
  ImpProdutoCusto_Fabrica in 'ImpProdutoCusto_Fabrica.pas' {ImpriProdutoCusto_Fabrica},
  ImpProduto_Pauta in 'ImpProduto_Pauta.pas' {ImpriProduto_Pauta},
  ImpVeiculos_Medidas in 'ImpVeiculos_Medidas.pas' {ImpriVeiculos_Medidas},
  ImpFinanceiro_APagar in '..\Geral\Contas\ImpFinanceiro_APagar.pas' {ImpriFinanceiro_APagar},
  ImpFinanceiro_AReceber in '..\Geral\Contas\ImpFinanceiro_AReceber.pas' {ImpriFinanceiro_AReceber},
  ImpEntrada_NotaFiscal in 'ImpEntrada_NotaFiscal.pas' {ImpriEntrada_NotaFiscal},
  ImpVeiculos_Estoque_Custos in 'ImpVeiculos_Estoque_Custos.pas' {ImpriVeiculos_Estoque_Custos},
  ImpNF_Entrada in 'ImpNF_Entrada.pas' {ImpriNF_Entrada},
  ImpClientes in 'ImpClientes.pas' {ImpriClientes},
  ImpProdutoCusto_Loja in 'ImpProdutoCusto_Loja.pas' {ImpriProdutoCusto_Loja},
  ImpFinanceiro_Boleto in '..\Geral\Contas\ImpFinanceiro_Boleto.pas' {ImpriFinanceiro_Boleto},
  ImpFinanceiro_Contador in '..\Geral\Contas\ImpFinanceiro_Contador.pas' {ImpriFinanceiro_Contador},
  ImpFinanceiro_LivroCaixa in '..\Geral\Contas\ImpFinanceiro_LivroCaixa.pas' {ImpriFinanceiro_LivroCaixa},
  ImpCarnePreImpresso in 'ImpCarnePreImpresso.pas' {ImpriCarnePreImpresso},
  ImpContrato in 'ImpContrato.pas' {ImpriContrato},
  ImpFinanceiro_Devedores in '..\Geral\Contas\ImpFinanceiro_Devedores.pas' {ImpriFinanceiro_Devedores},
  ImpProduto in 'ImpProduto.pas' {ImpriProduto},
  ImpBalanco in '..\Geral\ImpBalanco.pas' {ImpriBalanca},
  ImpCheque in '..\Geral\Contas\ImpCheque.pas' {ImpriCheque},
  ImpFicha in 'ImpFicha.pas' {ImpriFicha},
  ImpAgendaChamado in 'ImpAgendaChamado.pas' {ImpriAgendaChamado},
  ImpClientesSimplificado in 'ImpClientesSimplificado.pas' {ImpriClientesSimplificado},
  ImpEntradas in 'ImpEntradas.pas' {ImpriEntradas},
  ImpFinanceiro_Devedores2 in '..\Geral\Contas\ImpFinanceiro_Devedores2.pas' {ImpriFinanceiroDevedores},
  ImpAgenda in 'ImpAgenda.pas' {ImpriAgenda},
  ImpGrupo in 'ImpGrupo.pas' {ImpriGrupo},
  ImpTabelaFipe in '..\Aprocat\ImpTabelaFipe.pas' {ImpriTabelaFipe},
  ImpOcorrencia in '..\Aprocat\ImpOcorrencia.pas' {ImpriOcorrencia},
  ImpEtiquetas in '..\Aprocat\ImpEtiquetas.pas' {FrmEtiquetas},
  ImpOcorrencia_Espelho in '..\Aprocat\ImpOcorrencia_Espelho.pas' {ImpriOcorrencia_Espelho},
  ImpTabelaFipe_Valor in '..\Aprocat\ImpTabelaFipe_Valor.pas' {ImpriTabelaFipe_Valor},
  ImpCad_Equipamento in '..\Aprocat\ImpCad_Equipamento.pas' {ImpriCad_Equipamento},
  ImpClientes_Ativos in '..\Aprocat\ImpClientes_Ativos.pas' {ImpriClientes_Ativos},
  ImpEquipamentoAssociado in '..\Aprocat\ImpEquipamentoAssociado.pas' {ImpriEquipamentoAssociado},
  ImpOcorrencias in '..\Aprocat\ImpOcorrencias.pas' {ImpriOcorrencias},
  ImpEnvelope_QR in '..\Aprocat\ImpEnvelope_QR.pas' {ImpriEnvelope_QR},
  ImpNotasFiscais_Preriodo in 'ImpNotasFiscais_Preriodo.pas' {ImpriNotasFiscais_Periodo},
  RelEtiqueta in '..\Aprocat\RelEtiqueta.pas' {ImpriEtiqueta},
  RptCodigoBarras in 'RptCodigoBarras.pas' {Rpt_Barras},
  RelAuditoriaSINTEGRA_e_SPED in 'RelAuditoriaSINTEGRA_e_SPED.pas' {FrmAuditoriaSINTEGRA_e_SPED},
  ConCep in '..\Geral\ConCep.pas' {ConsuCep},
  Frame_ConVenda_Mestre in 'Frame_ConVenda_Mestre.pas' {Frame_ConsuVenda_Mestre},
  ConBancos in '..\Geral\ConBancos.pas' {ConsuBancos},
  ConProduto_Marca in '..\Geral\ConProduto_Marca.pas' {ConsuProduto_Marca},
  Frame_ConCor in 'Frame_ConCor.pas' {ConsuCor},
  ConContas in '..\Geral\Contas\ConContas.pas' {ConsuContas},
  ConEmpresa in '..\Geral\ConEmpresa.pas' {ConsuEmpresa},
  ConTelefones in '..\Geral\ConTelefones.pas' {ConsuTelefones},
  ConLocal in 'ConLocal.pas' {ConsuLocal},
  ConCidades in '..\Geral\ConCidades.pas' {ConsuCidadesOld},
  ConCaixa in '..\Geral\Contas\ConCaixa.pas' {ConsuCaixa},
  ConProduto_Tipo in 'ConProduto_Tipo.pas' {ConsuProduto_TipoOld},
  ConNF_CFOP in '..\Geral\ConNF_CFOP.pas' {ConsuNF_CFOP},
  ConNF_DadosAdicionais in 'ConNF_DadosAdicionais.pas' {ConsuNF_DadosAdicionais},
  ConProduto_Grade_Modelo in 'ConProduto_Grade_Modelo.pas' {ConsuProduto_Grade_Modelo},
  ConBalanco in 'ConBalanco.pas' {ConsuBalanco},
  ConUsuario in '..\Geral\ConUsuario.pas' {ConsuUsuario},
  Frame_ConProduto_Mestre in '..\Geral\Frame_ConProduto_Mestre.pas' {Frame_ConsuProduto_Mestre},
  Frame_ConPessoas_Mestre in '..\Geral\Frame_ConPessoas_Mestre.pas' {Frame_ConsuPessoas_Mestre},
  ConsultaPessoas in '..\Geral\ConsultaPessoas.pas' {FrmConsultaPessoas},
  ConMensalidade in 'ConMensalidade.pas' {ConsuMensalidade},
  ConCheque in '..\Geral\ConCheque.pas' {ConsuCheque},
  ConTipo_Impressao in 'ConTipo_Impressao.pas' {ConsuTipo_Impressao},
  ConProduto_Categoria in '..\Geral\ConProduto_Categoria.pas' {ConsuProduto_Categoria},
  ConSetor in 'ConSetor.pas' {ConsuSetor},
  ConFolha_Pagamento in '..\Geral\Contas\ConFolha_Pagamento.pas' {ConsuFolhaDePagamento},
  ConCondicaoPagto in '..\Geral\ConCondicaoPagto.pas' {ConsuCondicaoPagto},
  ConProduto_Grupo in '..\Geral\ConProduto_Grupo.pas' {ConsuProduto_Grupo},
  ConAcabamento in 'ConAcabamento.pas' {ConsuAcabamento},
  ConAgenda_FAQ in 'ConAgenda_FAQ.pas' {ConsuAgenda_FAQ},
  ConContrato_Tipo in '..\Geral\Contas\ConContrato_Tipo.pas' {ConsuContrato_Tipo},
  ConContrato in '..\Geral\Contas\ConContrato.pas' {ConsuContrato},
  ConProduto_Lote in 'ConProduto_Lote.pas' {ConsuProduto_Lote},
  ConSelecao_Lote in 'ConSelecao_Lote.pas' {FrmSelecao_Lote},
  ConUnidade in 'ConUnidade.pas' {ConsuUnidade},
  ConVenda_Situacao in 'ConVenda_Situacao.pas' {ConsuVenda_Situacao},
  ConPessoas_Tipo in '..\Geral\ConPessoas_Tipo.pas' {ConsuPessoas_Tipo},
  ConNF_NCM in '..\Geral\ConNF_NCM.pas' {ConsuNF_NCM},
  ConCentro_Trabalho in 'ConCentro_Trabalho.pas' {ConsuCentro_Trabalho},
  ConDRE_Classificacao in '..\Geral\Contas\ConDRE_Classificacao.pas' {ConsuDRE_Classificacao},
  ConDRE in '..\Geral\Contas\ConDRE.pas' {ConsuDRE},
  ConNota_Fiscal in 'ConNota_Fiscal.pas' {ConsuNota_Fiscal},
  ConOcorrencia in '..\Aprocat\ConOcorrencia.pas' {ConsuOcorrencia},
  Frame_ConEquipamento_Associacao in '..\Aprocat\Frame_ConEquipamento_Associacao.pas' {ConsuEquipamento_Associacao},
  Frame_ConTipoEquipamento in '..\Aprocat\Frame_ConTipoEquipamento.pas' {ConsuTipoEquipamento},
  Frame_ConSituacao in '..\Aprocat\Frame_ConSituacao.pas' {ConsuSituacao},
  Frame_ConAntifurto_Tipo in '..\Aprocat\Frame_ConAntifurto_Tipo.pas' {ConsuAntifurto_Tipo},
  Frame_ConPlano_Contas in '..\Geral\Frame_ConPlano_Contas.pas' {ConsuPlanoContas},
  ConEmail_Massa in 'ConEmail_Massa.pas' {ConsuEmail_Massa},
  Frame_ConProducao_Projeto in 'Frame_ConProducao_Projeto.pas' {Frame_ConsuPrucducao_Projeto},
  ConRecurso in 'ConRecurso.pas' {ConsuRecurso},
  ConsPesquisaAvancadaConPessoas in '..\Geral\ConsPesquisaAvancadaConPessoas.pas' {ConsuPesquisaAvancadaConPessoas},
  Frame_ConNotaFiscalEntrada in 'Frame_ConNotaFiscalEntrada.pas' {Frame_ConsuNota_Fiscal_Entrada},
  ConNF_Entrada in 'ConNF_Entrada.pas' {ConsuNF_Entrada},
  ConFinanceiro_Caixa in '..\Geral\Contas\ConFinanceiro_Caixa.pas' {ConsuFinanceiro_Caixa},
  Frame_ConFinanceiro_Mestre in '..\Geral\Contas\Frame_ConFinanceiro_Mestre.pas' {Frame_ConsuFinanceiro_Mestre},
  ConPais in '..\Geral\ConPais.pas' {ConsuPais},
  ConAgenda_Titulo in '..\Geral\ConAgenda_Titulo.pas' {ConsuAgenda_Titulo},
  ConHistoricoM in '..\Geral\ConHistoricoM.pas' {ConsuHistoricoM},
  ConTipo_Pagamento in '..\Geral\Contas\ConTipo_Pagamento.pas' {ConsuTipo_Pagamento},
  Frame_ConTipoOcorrencia in '..\Aprocat\Frame_ConTipoOcorrencia.pas' {ConsuTipoOcorrencia},
  ConLogSistema in '..\Geral\ConLogSistema.pas' {ConsuLogSistema},
  Frame_ConComissao in 'Frame_ConComissao.pas' {Frame_ConsuComissao},
  ConEquipamento_Tipo in 'ConEquipamento_Tipo.pas' {ConsuEquipamento_Tipo},
  ConNF_Natureza_Operacao in 'ConNF_Natureza_Operacao.pas' {ConsuNF_Natureza_Operacao},
  ConNF_Regime_Especial_Tributacao in 'ConNF_Regime_Especial_Tributacao.pas' {ConsuNF_Regime_Especial_Tributacao},
  ConEmail_Modelo in 'ConEmail_Modelo.pas' {ConsuEmail_Modelo},
  ConProduto_Estoque_Local in 'ConProduto_Estoque_Local.pas' {ConsuProduto_Estoque_Local},
  Frame_ConProducao_Mestre in 'Frame_ConProducao_Mestre.pas' {Frame_ConsuProducao_Mestre},
  ConFamilia in 'ConFamilia.pas' {ConsuFamilia},
  CadBalanco in 'CadBalanco.pas' {FrmBalanco},
  Frame_CadCor in 'Frame_CadCor.pas' {Frame_Cor},
  CadEmpresa in '..\Geral\CadEmpresa.pas' {FrmEmpresa},
  CadLocal in 'CadLocal.pas' {FrmLocal},
  CadProduto_Marca in '..\Geral\CadProduto_Marca.pas' {FrmProduto_Marca},
  CadProduto_Barras in 'CadProduto_Barras.pas' {FrmProduto_Barras},
  ConVenda_Tipo in '..\Geral\ConVenda_Tipo.pas' {ConsuVenda_Tipo},
  CadVenda_Tipo in '..\Geral\CadVenda_Tipo.pas' {FrmVenda_Tipo},
  CadNF_CFOP in '..\Geral\CadNF_CFOP.pas' {FrmNF_CFOP},
  CadNF_NCM in '..\Geral\CadNF_NCM.pas' {FrmNF_NCM},
  CadNF_DadosAdicionais in 'CadNF_DadosAdicionais.pas' {FrmNF_DadosAdicionais},
  CadProduto_Grade_Modelo in 'CadProduto_Grade_Modelo.pas' {FrmProduto_Grade_Modelo},
  CadProduto_Movimento in 'CadProduto_Movimento.pas' {FrmProduto_Movimento},
  CadFuncionario_Ponto in 'CadFuncionario_Ponto.pas' {FrmFuncionario_Ponto},
  CadFamilia in 'CadFamilia.pas' {FrmFamilia},
  CadCidades in 'CadCidades.pas' {FrmCidades},
  CadSetor in 'CadSetor.pas' {FrmSetor},
  CadUnidade in 'CadUnidade.pas' {FrmUnidade},
  CadMensalidade in 'CadMensalidade.pas' {FrmMensalidade},
  Frame_CadPessoas_Mestre in '..\Geral\Frame_CadPessoas_Mestre.pas' {Frame_Pessoas_Mestre},
  CadPessoas_Tipo in '..\Geral\CadPessoas_Tipo.pas' {FrmPessoas_Tipo},
  CadPessoasFrameFerias in '..\Geral\CadPessoasFrameFerias.pas' {FrmFramePessoasFerias: TFrame},
  CadPessoasFramePensaoAlimenticia in '..\Geral\CadPessoasFramePensaoAlimenticia.pas' {FrmFramePessoasPensaoAlimenticia: TFrame},
  CadPessoasFrameSalarios in '..\Geral\CadPessoasFrameSalarios.pas' {FrmFramePessoasSalarios: TFrame},
  CadPessoasFrameBeneficiarios in '..\Geral\CadPessoasFrameBeneficiarios.pas' {FrmFramePessoasBeneficiarios: TFrame},
  CadPessoasFrameAnotacoesTrab in '..\Geral\CadPessoasFrameAnotacoesTrab.pas' {FrmFramePessoasAnotacoesTrabalho: TFrame},
  CadPessoasFrameHorarios in '..\Geral\CadPessoasFrameHorarios.pas' {FrmFramePessoasHorarios: TFrame},
  CadPessoasFrameDadosAdicionais in '..\Geral\CadPessoasFrameDadosAdicionais.pas' {FrmFramePessoasDadosAdicionais: TFrame},
  CadPessoasFrameDadosPessoais in '..\Geral\CadPessoasFrameDadosPessoais.pas' {FrmFramePessoasDadosPessoais: TFrame},
  CadPessoasFrameHistoricoCompras in '..\Geral\CadPessoasFrameHistoricoCompras.pas' {FrmFramePessoasHistoricoDeCompras: TFrame},
  CadPessoasFrameFinanceiro in '..\Geral\CadPessoasFrameFinanceiro.pas' {FrmFramePessoasFinanceiro: TFrame},
  CadPessoasFrameEquipamento in '..\Geral\CadPessoasFrameEquipamento.pas' {FrmFramePessoasEquipamento: TFrame},
  CadPessoasFrameConjuge in '..\Geral\CadPessoasFrameConjuge.pas' {FrmFramePessoasConjuge: TFrame},
  CadPessoasFrameContatos in '..\Geral\CadPessoasFrameContatos.pas' {FrmFramePessoasContatos: TFrame},
  CadPessoasFrameVendas in '..\Geral\CadPessoasFrameVendas.pas' {FrmFramePessoasVendas: TFrame},
  CadPessoasFrameDemissao in '..\Geral\CadPessoasFrameDemissao.pas' {FrmFramePessoasDemissao: TFrame},
  CadPessoasFrameCrediario in '..\Geral\CadPessoasFrameCrediario.pas' {FrmFramePessoasCrediario: TFrame},
  CadPessoasFrameTabelaDePrecos in '..\Geral\CadPessoasFrameTabelaDePrecos.pas' {FrmFramePessoasTabelaDePrecos: TFrame},
  CadPessoasFrameAgrupamento in '..\Geral\CadPessoasFrameAgrupamento.pas' {FrmFramePessoasAgrupamento: TFrame},
  CadPessoasFrameFichaPonto in '..\Geral\CadPessoasFrameFichaPonto.pas' {FrmFramePessoasFichaPonto: TFrame},
  CadPessoasFrameFuncoes in '..\Geral\CadPessoasFrameFuncoes.pas' {FrmFramePessoasFuncoes: TFrame},
  CadPessoasFrameEndCorrespondencia in '..\Geral\CadPessoasFrameEndCorrespondencia.pas' {FrmFramePessoasEndCorrespondencia: TFrame},
  CadVendaFrameNotaFiscal in 'CadVendaFrameNotaFiscal.pas' {FrmVendaFrameNotaFiscal: TFrame},
  CadPessoasFrameRepresentante in '..\Geral\CadPessoasFrameRepresentante.pas' {FrmFramePessoasRepresentantes: TFrame},
  Frame_CadConciliacao_Bancaria in '..\Geral\Contas\Frame_CadConciliacao_Bancaria.pas' {Frame_Conciliacao_Bancaria},
  CadBancos in '..\Geral\CadBancos.pas' {FrmBancos},
  CadTipo_Impressao in 'CadTipo_Impressao.pas' {FrmTipo_Impressao},
  CadNotaFiscal in 'CadNotaFiscal.pas' {FrmNotaFiscal},
  CadProduto_Categoria in '..\Geral\CadProduto_Categoria.pas' {FrmProduto_Categoria},
  CadFolha_Pagamento_Grupo in '..\Geral\Contas\CadFolha_Pagamento_Grupo.pas' {FrmFolhaDePagamentoGrupo},
  Frame_CadProduto_Mestre in 'Frame_CadProduto_Mestre.pas' {Frame_Produto_Mestre},
  CadVenda_Situacao in 'CadVenda_Situacao.pas' {FrmVenda_Situacao},
  CadBackup in '..\Geral\CadBackup.pas' {FrmBackup},
  CadPessoasFrameHabilidades in '..\Geral\CadPessoasFrameHabilidades.pas' {FrmFramePessoasHabilidades: TFrame},
  CadPessoasFrameWr2Acessos in '..\Geral\CadPessoasFrameWr2Acessos.pas' {TFrmFramePessoasWr2Acessos: TFrame},
  CadVendaFrameAgrupamento in 'CadVendaFrameAgrupamento.pas' {FrmVendaFrameAgrupamento: TFrame},
  CadPessoasFrameEmail in '..\Geral\CadPessoasFrameEmail.pas' {FrmFramePessoasEmail: TFrame},
  CadProduto_Grupo in '..\Geral\CadProduto_Grupo.pas' {FrmProduto_Grupo},
  CadContas in '..\Geral\Contas\CadContas.pas' {FrmContas},
  CadCondicaoPagto in '..\Geral\CadCondicaoPagto.pas' {FrmCondicaoPagto},
  CadAcabamento in 'CadAcabamento.pas' {FrmAcabamento},
  CadContrato_Tipo in '..\Geral\Contas\CadContrato_Tipo.pas' {FrmContrato_Tipo},
  CadProduto_Lote in 'CadProduto_Lote.pas' {FrmProduto_Lote},
  Frame_CadComissao in 'Frame_CadComissao.pas' {FrmComissao},
  CadCentro_Trabalho in 'CadCentro_Trabalho.pas' {FrmCentro_Trabalho},
  CadVenda_Produto in 'CadVenda_Produto.pas' {FrmVenda_Produto},
  CadOcorrencia in '..\Aprocat\CadOcorrencia.pas' {FrmOcorrencia},
  Frame_CadEquipamento_Associacao in '..\Aprocat\Frame_CadEquipamento_Associacao.pas' {Frame_Equipamento_Associacao},
  CadRateio in '..\Aprocat\CadRateio.pas' {FrmRateio},
  Frame_CadTipoequipamento in '..\Aprocat\Frame_CadTipoequipamento.pas' {Frame_TipoEquipamentos},
  Frame_CadSituacao in '..\Aprocat\Frame_CadSituacao.pas' {Frame_Situacao},
  CadDRE in '..\Geral\Contas\CadDRE.pas' {FrmDRE},
  CadDRE_Classificacao in '..\Geral\Contas\CadDRE_Classificacao.pas' {Frame_DRE_Classificacao},
  Frame_CadVenda_Mestre in 'Frame_CadVenda_Mestre.pas' {Frame_Venda_Mestre},
  Frame_CadTipoOcorrencia in '..\Aprocat\Frame_CadTipoOcorrencia.pas' {Frame_TipoOcorrencia},
  CadLogSistema in '..\Geral\CadLogSistema.pas' {FrmLogSistema},
  Frame_CadTabela_Valor in '..\Aprocat\Frame_CadTabela_Valor.pas' {Frame_Tabela_Valor},
  Frame_CadProducao in 'Frame_CadProducao.pas' {Frame_Cad_Producao},
  CadEncaminhar in 'CadEncaminhar.pas' {FrmEncaminhar},
  CadMalaDireta in 'CadMalaDireta.pas' {FrmMalaDireta},
  Frame_CadRateio_Custo_Old in '..\Geral\Contas\Frame_CadRateio_Custo_Old.pas' {FrmRateioCusto},
  CadNF_Natureza_Operacao in 'CadNF_Natureza_Operacao.pas' {FrmNF_Natureza_Operacao},
  CadNF_Regime_Especial_Tributacao in 'CadNF_Regime_Especial_Tributacao.pas' {FrmNF_Regime_Especial_Tributacao},
  Frame_CadAntifurto_Tipo in '..\Aprocat\Frame_CadAntifurto_Tipo.pas' {Frame_Antifurto_Tipo},
  Frame_CadPlano_Contas in '..\Geral\Frame_CadPlano_Contas.pas' {FrmPlanoContas},
  CadEmail_Massa in 'CadEmail_Massa.pas' {FrmEmail_Massa},
  Frame_CadProducao_Projeto in 'Frame_CadProducao_Projeto.pas' {FrmProjeto},
  CadPessoasFrameFuncionarioGeral in '..\Geral\CadPessoasFrameFuncionarioGeral.pas' {FrmFramePessoasFuncionarioGeral: TFrame},
  CadRecurso in 'CadRecurso.pas' {FrmRecurso},
  CadPais in '..\Geral\CadPais.pas' {FrmPais},
  CadProduto_Tipo in 'CadProduto_Tipo.pas' {FrmProduto_Tipo},
  CadProduto_Estoque_Local in 'CadProduto_Estoque_Local.pas' {FrmProduto_Estoque_Local},
  CadTelefones in '..\Geral\CadTelefones.pas' {FrmTelefones},
  CadAgenda_Titulo in '..\Geral\CadAgenda_Titulo.pas' {FrmAgenda_Titulo},
  CadTipo_Pagamento in '..\Geral\Contas\CadTipo_Pagamento.pas' {FrmTipo_Pagamento},
  CadEmail_Modelo in 'CadEmail_Modelo.pas' {FrmEmail_Modelo},
  Recibo in '..\Geral\Contas\Recibo.pas' {FrmRecibo},
  Cheque in 'Cheque.pas' {FrmCheque},
  Financeiro_Contas_Escolha in '..\Geral\Contas\Financeiro_Contas_Escolha.pas' {FrmFinanceiro_Contas_Escolha},
  Financeiro_Caixa in '..\Geral\Contas\Financeiro_Caixa.pas' {FrmFinanceiro_Caixa},
  Frame_CadFinanceiro in '..\Geral\Contas\Frame_CadFinanceiro.pas' {Frame_Financeiro},
  Financeiro_Recebimento in '..\Geral\Contas\Financeiro_Recebimento.pas' {FrmFinanceiro_Recebimento},
  Financeiro_AReceber in '..\Geral\Contas\Financeiro_AReceber.pas' {FrmFinanceiro_AReceber},
  Financeiro_APagar in '..\Geral\Contas\Financeiro_APagar.pas' {FrmFinanceiro_APagar},
  Financeiro_Cheque in '..\Geral\Contas\Financeiro_Cheque.pas' {FrmFinanceiro_Cheque},
  Financeiro_Boleto in '..\Geral\Contas\Financeiro_Boleto.pas' {FrmFinanceiro_BoletoOld},
  Financeiro_Historico in '..\Geral\Contas\Financeiro_Historico.pas' {FrmFinanceiroHistorico},
  NFe in 'NFe.pas' {FrmNFe},
  NFe_Status in 'NFe_Status.pas' {frmStatus},
  NF_Entrada in 'NF_Entrada.pas' {FrmNF_Entrada},
  NFeDuplicidade in 'NFeDuplicidade.pas' {FrmNFeDuplicidade},
  frFrameAnexos in '..\Geral\frFrameAnexos.pas' {FrameAnexos: TFrame},
  frFrameCustos in 'frFrameCustos.pas' {FrameCustos: TFrame},
  FrFrameComposicao in 'FrFrameComposicao.pas' {FrmFrameComposicao: TFrame},
  frFrameHistorico in '..\Geral\frFrameHistorico.pas' {FrameHistorico: TFrame},
  About in '..\Geral\About.pas' {FrmAbout},
  Aguarde in '..\Geral\Aguarde.pas' {FrmAguarde},
  Splash in 'Splash.pas' {FrmSplash},
  CaminhoBanco in '..\Geral\CaminhoBanco.pas' {FrmCaminhoBanco},
  Registro in '..\Geral\Registro.pas' {FrmRegistro},
  Unit_SQL in '..\Geral\Unit_SQL.pas' {FrmUpgrade},
  MsgConSpc in 'MsgConSpc.pas' {FrmMsgConSpc},
  Relatorios in 'Relatorios.pas' {FrmRelatorios},
  Email in '..\Geral\Email.pas' {FrmEMail},
  EmailDevExpressFuncoes in 'EmailDevExpressFuncoes.pas',
  Email_Configuracoes in '..\Geral\Email_Configuracoes.pas' {FrmEmailConfiguracao},
  EmailEnvio in '..\Geral\EmailEnvio.pas' {FrmEmailEnvio},
  VisualizadorEmail in '..\Geral\VisualizadorEmail.pas' {FrmVisualizadorEmail},
  AgendaEditor in 'AgendaEditor.pas' {FrmAgendaEditor},
  AgendaHistorico in 'AgendaHistorico.pas' {FrmAgendaHistorico},
  AgendaEditorRapido in 'AgendaEditorRapido.pas' {FrmAgendaEditorRapido},
  Agenda_Financeiro in '..\Geral\Agenda_Financeiro.pas' {FrmAgendaFinanceiro},
  Agenda_PostAgenda in '..\Geral\Agenda_PostAgenda.pas' {FrmAgendaPostAgenda},
  AgendaEventoAnexos in '..\Geral\AgendaEventoAnexos.pas' {FrmAgendaEventoAnexo},
  CopiarConfigGrid in '..\Geral\CopiarConfigGrid.pas' {FrmCopiarConfigGrid},
  PontoEletronico in '..\Geral\PontoEletronico.pas' {FrmPontoEletronico},
  ConsultaCNPJCPF in '..\Geral\ConsultaCNPJCPF.pas' {FrmConsultaCNPJCPF},
  BigData in '..\Geral\BigData.pas' {FrmBigData},
  ConsultaProdutosBigData in '..\Geral\ConsultaProdutosBigData.pas' {FrmConsultaProdutosBigData},
  Validacoes in 'Validacoes.pas' {FrmValidacoes},
  InspetorDeObjetos in '..\Geral\InspetorDeObjetos.pas' {FrmInspetorDeObjetos},
  Senha in '..\Geral\Senha.pas' {FrmSenha},
  FalhaConexaoBanco in '..\Geral\FalhaConexaoBanco.pas' {FrmFalhaConexaoBanco},
  MesclarPessoas in 'MesclarPessoas.pas' {FrmMesclarPessoas},
  EquipamentoHistorico in '..\Aprocat\EquipamentoHistorico.pas' {FrmEquipamentoHistorico},
  CadProduto_Wizard in 'CadProduto_Wizard.pas' {FrmProduto_Wizard},
  Certificado in 'Certificado.pas' {FrmSelecionarCertificado},
  PlanejamentoScheduler in '..\Componentes\PlanejamentoScheduler.pas',
  GeraEmailsBoletos in 'GeraEmailsBoletos.pas' {FrmGeraEmailsBoletos},
  EntradaTempo in '..\Geral\EntradaTempo.pas' {FrmEntradaTempo},
  NF_Entrada_Produtos in 'NF_Entrada_Produtos.pas' {FrmNF_Entrada_Produtos},
  TextoObservacao in 'TextoObservacao.pas' {FrmObservacao},
  PerguntaEstado in '..\Geral\PerguntaEstado.pas' {FrmPerguntaEstado},
  Financeiro_Credito in '..\Geral\Contas\Financeiro_Credito.pas' {FrmFinanceiroCredito},
  Financeiro_CaixaNew in '..\Geral\Contas\Financeiro_CaixaNew.pas' {FrmFinanceiro_CaixaNew},
  ProdutoTipoSelecao in 'ProdutoTipoSelecao.pas' {FrmProdutoTipoSelecao},
  SAT in 'SAT.pas' {FrmSAT},
  SATImprimirCancelamento in 'SATImprimirCancelamento.pas' {FrmSATImprimir},
  DebugCounter in '..\Geral\DebugCounter.pas' {FrmDebugCounter},
  AguardeMestre in '..\Geral\AguardeMestre.pas' {FrmAguardeMestre},
  AguardeConsulta in '..\Geral\AguardeConsulta.pas' {FrmAguardeConsulta},
  ConfiguracoesM in '..\Geral\ConfiguracoesM.pas' {FrmConfiguracoesM},
  Principal in 'Principal.pas' {FrmPrincipal},
  Produto_Preco in 'Produto_Preco.pas' {FrmProduto_Preco},
  Frame_ConArquivos_Relatorio in 'Frame_ConArquivos_Relatorio.pas' {FrameConsuArquivos_Relatorio},
  Frame_CadArquivos_Relatorio in 'Frame_CadArquivos_Relatorio.pas' {FrmArquivos_Relatorio},
  CadProduto_Markup in 'CadProduto_Markup.pas' {FrmProduto_Markup},
  ConProduto_Markup in 'ConProduto_Markup.pas' {ConsuProduto_Markup},
  CadConfiguracao_Componente in 'CadConfiguracao_Componente.pas' {FrmConfiguracao_Componente},
  ConConfiguracao_Componente in 'ConConfiguracao_Componente.pas' {ConsuConfiguracao_Componente},
  CadConfiguracao_Regra in 'CadConfiguracao_Regra.pas' {FrmConfiguracao_Regra},
  ConConfiguracao_Regra in 'ConConfiguracao_Regra.pas' {ConsuConfiguracao_Regra},
  CadConfiguracao_Acoes in 'CadConfiguracao_Acoes.pas' {FrmConfiguracao_Acoes},
  ConConfiguracao_Acoes in 'ConConfiguracao_Acoes.pas' {ConsuConfiguracao_Acoes},
  CadConfiguracoes_Grid in 'CadConfiguracoes_Grid.pas' {FrmConfiguracoes_Grid},
  ConConfiguracoes_Grid in 'ConConfiguracoes_Grid.pas' {ConsuConfiguracoes_Grid},
  CadProducao_Situacao in 'CadProducao_Situacao.pas' {FrmProducao_Situacao},
  ConProducao_Situacao in 'ConProducao_Situacao.pas' {ConsuProducao_Situacao},
  CadProducao_Template in 'CadProducao_Template.pas' {FrmProducao_Template},
  ConProducao_Template in 'ConProducao_Template.pas' {ConsuProducao_Template},
  CadVenda_Estagio in 'CadVenda_Estagio.pas' {FrmVenda_Estagio},
  ConVenda_Estagio in 'ConVenda_Estagio.pas' {ConsuVenda_Estagio},
  ConProducao_Acao in 'ConProducao_Acao.pas' {ConsuProducao_Acao},
  CadProducao_Acao in 'CadProducao_Acao.pas' {FrmProducao_Acao},
  ConProducao_Marcador in 'ConProducao_Marcador.pas' {ConsuProducao_Marcador},
  CadProducao_Marcador in 'CadProducao_Marcador.pas' {FrmProducao_Marcador},
  CadPessoas_Grupo in '..\Geral\CadPessoas_Grupo.pas' {FrmPessoas_Grupo},
  ConPessoas_Grupo in '..\Geral\ConPessoas_Grupo.pas' {ConsuPessoas_Grupo},
  CadProduto_Tabela in 'CadProduto_Tabela.pas' {FrmProduto_Tabela},
  ConProduto_Tabela in 'ConProduto_Tabela.pas' {ConsuProduto_Tabela},
  TratarImagem in 'TratarImagem.pas' {FrmTratarImagem},
  ConConfiguracao_Filtro in 'ConConfiguracao_Filtro.pas' {ConsuConfiguracao_Filtro},
  ConConfiguracao_Agrupamento in 'ConConfiguracao_Agrupamento.pas' {ConsuConfiguracao_Agrupamento},
  CadConfiguracao_Filtro in 'CadConfiguracao_Filtro.pas' {FrmConfiguracao_Filtro},
  CadConfiguracao_Agrupamento in 'CadConfiguracao_Agrupamento.pas' {FrmConfiguracao_Agrupamento},
  Excel in 'Excel.pas' {FrmExcel},
  CadProducao_Roteiro in 'CadProducao_Roteiro.pas' {FrmProducao_Roteiro},
  ConProducao_Roteiro in 'ConProducao_Roteiro.pas' {ConsuProducao_Roteiro},
  ConProducao_Roteiro_Pergunta in 'ConProducao_Roteiro_Pergunta.pas' {ConsuProducao_Roteiro_Pergunta},
  CadProducao_Roteiro_Pergunta in 'CadProducao_Roteiro_Pergunta.pas' {FrmProducao_Roteiro_Pergunta},
  ExcelRealatorio in 'ExcelRealatorio.pas' {FrmExcelRealatorio},
  ConFolha_Pagamento_Grupo in '..\Geral\Contas\ConFolha_Pagamento_Grupo.pas' {ConsuFolha_Pagamento_Grupo},
  wrFuncoesComponentes in 'D:\Programas Base\Componentes\wrFuncoesComponentes.pas',
  FrFrameTabelaPreco in 'FrFrameTabelaPreco.pas' {FrmFrameTabelaPreco: TFrame},
  FrFrameMestre in '..\Geral\FrFrameMestre.pas' {FrmFrameMestre: TFrame},
  CadProdutoFrameEstoque in 'CadProdutoFrameEstoque.pas' {FrameCadProduto_Estoque: TFrame},
  Agenda in 'Agenda.pas' {FrmAgenda},
  FrFrameCentroCustos in 'FrFrameCentroCustos.pas' {FrmFrameCentroCustos: TFrame},
  CadSpreadSheet_Referencia in 'CadSpreadSheet_Referencia.pas' {FrmSpreadSheet_Referencia},
  ConSpreadSheet_Referencia in 'ConSpreadSheet_Referencia.pas' {ConsuSpreadSheet_Referencia},
  Logo in 'Logo.pas' {FrmLogo},
  uWRNotaFiscal in '..\Componentes\uWRNotaFiscal.pas',
  wrFuncoes_Office in 'wrFuncoes_Office.pas',
  CadSped in 'CadSped.pas' {FrmSped},
  ConSped in 'ConSped.pas' {ConsSped},
  frFrameLucro in 'frFrameLucro.pas' {FormLucroPrevisto},
  FrmUnidade_Teste_Conversao in 'FrmUnidade_Teste_Conversao.pas' {FormRendimento_Formula},
  FrmExtras in 'FrmExtras.pas' {FormExtras},
  FrmRendimento in 'FrmRendimento.pas' {FormRendimento},
  CadNF_Erros in 'CadNF_Erros.pas' {FrmNF_Erros},
  CadNF_Provedor in 'CadNF_Provedor.pas' {FrmNF_Provedor},
  ConNF_Erros in 'ConNF_Erros.pas' {ConsuNF_Erros},
  ConNF_Provedor in 'ConNF_Provedor.pas' {ConsuNF_Provedor},
  Frame_ConBI_KPI in 'Frame_ConBI_KPI.pas' {ConsuBI_KPI},
  Frame_CadBI_KPI in 'Frame_CadBI_KPI.pas' {FrmBI_KPI},
  FrmMarkup in 'FrmMarkup.pas' {FormMarkup},
  frFrameImposto in 'frFrameImposto.pas' {sa: TFrame},
  wrTabelasCampos in '..\WR Integrador\wrTabelasCampos.pas',
  CadNF_CST in 'CadNF_CST.pas' {FrmNF_CST},
  ConNF_CST in 'ConNF_CST.pas' {ConsuNF_CST},
  CadNF_CEST in 'CadNF_CEST.pas' {FrmNF_CEST},
  ConNF_CEST in 'ConNF_CEST.pas' {ConsuNF_CEST},
  CadNF_CNAE in 'CadNF_CNAE.pas' {FrmNF_CNAE},
  ConNF_CNAE in 'ConNF_CNAE.pas' {ConsuNF_CNAE},
  CadCentro_Custo in 'CadCentro_Custo.pas' {FrmCentro_Custo},
  ConCentro_Custo in 'ConCentro_Custo.pas' {ConsuCentro_Custo},
  CadFinanceiro_Rateio in 'CadFinanceiro_Rateio.pas' {FrmFinanceiro_Rateio},
  FrFrameVendedor in 'FrFrameVendedor.pas' {FrmFrameVendedor},
  FrmCentroCustos in 'FrmCentroCustos.pas' {FrameCentroCustos},
  FrFrameMarkupDashBoard in 'FrFrameMarkupDashBoard.pas' {FrmMarkupDashBoard},
  FrFrameDashboards in 'FrFrameDashboards.pas' {FrameDashboards},
  FrFrameDespesaFinanceira in 'FrFrameDespesaFinanceira.pas' {FrmFrameDespesaFinanceira: TFrame},
  Frame_ConMensagens in 'Frame_ConMensagens.pas' {Frame_ConsuMensagens},
  CadHistorico_Notificacao in 'CadHistorico_Notificacao.pas' {FrmHistorico_Notificacao},
  ConPlanilha_Tempo in 'ConPlanilha_Tempo.pas' {ConsuPlanilha_Tempo},
  CadPlanilha_Tempo in 'CadPlanilha_Tempo.pas' {FrmPlanilha_Tempo},
  ConsPesquisaAvancada in '..\Geral\ConsPesquisaAvancada.pas' {ConsuPesquisaAvancada},
  FrFrameKanban in 'FrFrameKanban.pas' {FrameKanban: TFrame},
  Frame_CadVenda_Venda in 'Frame_CadVenda_Venda.pas' {Frame_Venda_Venda},
  NFSe in 'NFSe.pas' {FrmNFSe},
  CadProducao_Estagio in 'CadProducao_Estagio.pas' {FrmProducao_Estagio},
  ConProducao_Estagio in 'ConProducao_Estagio.pas' {ConsuProducao_Estagio},
  CadProducao_Motivo in 'CadProducao_Motivo.pas' {FrmProducao_Motivo},
  ConProducao_Motivo in 'ConProducao_Motivo.pas' {ConsuProducao_Motivo},
  frFrameVendaNFSe in 'frFrameVendaNFSe.pas' {FrameVendaNFSe: TFrame},
  FrmProducaoFaturar in 'FrmProducaoFaturar.pas' {FormProducaoFaturar},
  FrmNFeventos in 'FrmNFeventos.pas' {FormNFeventos},
  Producao_Fila in 'Producao_Fila.pas' {FrmProducao_Fila},
  FrmRegistroAviso in 'FrmRegistroAviso.pas' {FormRegistroAviso},
  CadEquipamento_Rateio in 'CadEquipamento_Rateio.pas' {FrmEquipamento_Rateio},
  frFrameAnexosConfiguracao in 'frFrameAnexosConfiguracao.pas' {FrameAnexosConfiguracao},
  ConEquipamento_Rateio in 'ConEquipamento_Rateio.pas' {ConsuEquipamento_Rateio},
  PDV_Pagamento in 'PDV_Pagamento.pas' {FrmPDV_Pagamento},
  ChangeLog in 'ChangeLog.pas' {FrmChangeLog},
  Frame_ConConciliacao_Bancaria_Arquivos in 'Frame_ConConciliacao_Bancaria_Arquivos.pas' {Consu1Conciliacao_Bancaria_Arquivos},
  Menu in 'Menu.pas' {FrmMenu},
  Frame_Painel in 'Frame_Painel.pas' {Painel_Frame: TFrame},
  Frame_Painel_Venda_Funcionario in 'Frame_Painel_Venda_Funcionario.pas' {Painel_Venda_Funionario: TFrame},
  Frame_Painel_Empresa in 'Frame_Painel_Empresa.pas' {Painel_Empresa: TFrame},
  Frame_Painel_Venda_Produto_Tipo in 'Frame_Painel_Venda_Produto_Tipo.pas' {Painel_Venda_Produto_Tipo: TFrame},
  Frame_Painel_Mestre in 'Frame_Painel_Mestre.pas' {Painel_Mestre: TFrame},
  frMenuTEF in 'frMenuTEF.pas' {FormMenuTEF},
  frObtemCampo in 'frObtemCampo.pas' {FormObtemCampo},
  frExibeMensagem in 'frExibeMensagem.pas' {FormExibeMensagem},
  frFrameAnexosPessoas in 'frFrameAnexosPessoas.pas' {FrameAnexosPessoas: TFrame},
  frFrameAnexosFuncionario in 'frFrameAnexosFuncionario.pas' {FrameAnexosFuncionario: TFrame},
  frFrameAnexosVenda in 'frFrameAnexosVenda.pas' {FrameAnexosVenda: TFrame},
  frFrameAnexosProduto in 'frFrameAnexosProduto.pas' {FrameAnexosProduto: TFrame},
  frFrameAnexosProducao in 'frFrameAnexosProducao.pas' {FrameAnexosProducao: TFrame},
  Classes.Venda in 'app\Classes\Classes.Venda.pas',
  Classes.Venda.TEF in 'app\Classes\Classes.Venda.TEF.pas',
  frFrameAnexosVenda_Produto in 'frFrameAnexosVenda_Produto.pas' {FrameAnexosVenda_Produto: TFrame},
  CadMeta in 'CadMeta.pas' {FrmMeta},
  ConMeta in 'ConMeta.pas' {ConsuMeta},
  Frame_Painel_Venda_Categoria in 'Frame_Painel_Venda_Categoria.pas' {Painel_Venda_Categoria: TFrame},
  frFrameAnexosEquipamentos in 'frFrameAnexosEquipamentos.pas' {FrameAnexosEquipamentos: TFrame},
  frFrameAnexosOcorrencias in 'frFrameAnexosOcorrencias.pas' {FrameAnexosOcorrencias: TFrame},
  frFrameAnexosRateio in 'frFrameAnexosRateio.pas' {FrameAnexosRateio: TFrame},
  PDV_Pagamento_Incluir in 'PDV_Pagamento_Incluir.pas' {FrmPDV_Pagamento_Incluir},
  frFrameAnexosAgenda in 'frFrameAnexosAgenda.pas' {FrameAnexosAgenda: TFrame},
  CadFinanceiro_Cartao in 'CadFinanceiro_Cartao.pas' {FrmFinanceiro_Cartao},
  ConFinanceiro_Cartao in 'ConFinanceiro_Cartao.pas' {ConsuFinanceiro_Cartao},
  Frame_Painel_Estoque_Movimento in 'Frame_Painel_Estoque_Movimento.pas' {Painel_Estoque_Movimento: TFrame},
  ConVenda_Financeiro_Tef in 'ConVenda_Financeiro_Tef.pas' {ConsuVendaFinanceiroTef},
  FrmUnidadeSubunidade in 'FrmUnidadeSubunidade.pas' {FormUnidadeSubunidade},
  Base_Produto in 'Base_Produto.pas' {FrmProduto},
  Frame_Con in '..\Geral\Frame_Con.pas' {Consu_Frame},
  ConsM in '..\Geral\ConsM.pas' {ConsuM},
  Frame_ConProduto_Variacao in 'Frame_ConProduto_Variacao.pas' {ConsuProduto_Variacao_Frame: TFrame},
  Frame_ConProduto_ProdutoSimples in 'Frame_ConProduto_ProdutoSimples.pas' {ConsuProduto_ProdutoSimples: TFrame},
  Frame_ConProduto_Personalizado in 'Frame_ConProduto_Personalizado.pas' {ConsuProduto_Personalizado_Frame: TFrame},
  Frame_ConProduto_Composicao in 'Frame_ConProduto_Composicao.pas' {ConsuProduto_Composicao_Frame: TFrame},
  Frame_ConProduto_Patrimonio in 'Frame_ConProduto_Patrimonio.pas' {ConsuProduto_Patrimonio_Frame: TFrame},
  CadM in '..\Geral\CadM.pas' {FrmCadM},
  frFrameProdutoSubUnidade in 'frFrameProdutoSubUnidade.pas' {FrameProdutoSubUnidade: TFrame},
  FrFrameProdutoVariacaoTabela in 'FrFrameProdutoVariacaoTabela.pas' {FrmFrameMestre1: TFrame},
  Base_Produto_Modal in 'Base_Produto_Modal.pas' {FrmProduto_Modal},
  Frame_CadProduto_Composicao in 'Frame_CadProduto_Composicao.pas' {FrmProduto_Composicao_Frame: TFrame},
  Frame_CadProduto_Variacao in 'Frame_CadProduto_Variacao.pas' {Frame_FrmProduto_Variacao: TFrame},
  Frame_CadProduto_Patrimonio in 'Frame_CadProduto_Patrimonio.pas' {FrmProduto_Patrimonio_Frame: TFrame},
  Frame_CadProduto_ProdutoSimples in 'Frame_CadProduto_ProdutoSimples.pas' {FrmProduto_ProdutoSimples_Frame: TFrame},
  Frame_CadProduto_Personalizado in 'Frame_CadProduto_Personalizado.pas' {FrmProduto_Personalizado_Frame: TFrame},
  frFrameVariacao in 'frFrameVariacao.pas' {FrmFrameVariacao: TFrame},
  frFrameProduto_Personalizado in 'frFrameProduto_Personalizado.pas' {FrmFrameProduto_Personalizado: TFrame},
  frFrameVendaPessoa in 'frFrameVendaPessoa.pas' {FrameVendaPessoa: TFrame},
  CadProduto_Personalizado_Panel in 'CadProduto_Personalizado_Panel.pas' {FrmProduto_Personalizado_Panel},
  Frame_VendaTipoSelecao in 'Frame_VendaTipoSelecao.pas' {FrameVendaTipoSelecao},
  FrmProdutoVariacaoPanel in 'FrmProdutoVariacaoPanel.pas' {FrmProdutoVariacaoPanel},
  Base_Estoque in 'Base_Estoque.pas' {FrmEstoque},
  Base_Estoque_Modal in 'Base_Estoque_Modal.pas' {FrmEstoque_Modal},
  Frame_ConEstoque_Mestre in 'Frame_ConEstoque_Mestre.pas' {Frame_ConsuEstoque_Mestre: TFrame},
  Frame_ConRelNF_Entrada_Produto in 'Frame_ConRelNF_Entrada_Produto.pas' {Frame_ConsuRelNF_Entrada_Produto: TFrame},
  Frame_ConProduto_Compra in 'Frame_ConProduto_Compra.pas' {Frame_ConsuProduto_Compra: TFrame},
  Frame_ConProduto_Servico in 'Frame_ConProduto_Servico.pas' {ConsuProduto_Servico_Frame: TFrame},
  Frame_ConProduto_MateriaPrima in 'Frame_ConProduto_MateriaPrima.pas' {ConsuProduto_MateriaPrima_Frame: TFrame},
  Frame_ConProduto_UsoEConsumo in 'Frame_ConProduto_UsoEConsumo.pas' {ConsuProduto_UsoEConsumo_Frame: TFrame},
  Frame_ConProduto_Venda in 'Frame_ConProduto_Venda.pas' {Frame_ConsuProduto_Venda: TFrame},
  Base_Produto_Venda in 'Base_Produto_Venda.pas' {FrmProduto_Venda},
  Base_Produto_Venda_Modal in 'Base_Produto_Venda_Modal.pas' {FrmProduto_Venda_Modal},
  Base_Produto_Compra in 'Base_Produto_Compra.pas' {FrmProduto_Compra},
  Base_Produto_Compra_Modal in 'Base_Produto_Compra_Modal.pas' {FrmProduto_Compra_Modal},
  Frame_CadProduto_Servico in 'Frame_CadProduto_Servico.pas' {FrmProduto_Servico_Frame: TFrame},
  Frame_CadProduto_UsoEConsumo in 'Frame_CadProduto_UsoEConsumo.pas' {FrmProduto_UsoEConsumo_Frame: TFrame},
  Frame_CadProduto_MateriaPrima in 'Frame_CadProduto_MateriaPrima.pas' {FrmProduto_MateriaPrima_Frame: TFrame},
  Base_API_OImpresso in 'Base_API_OImpresso.pas' {FrmAPI_OImpresso},
  Frame_CadAPI_OImpresso_Mestre in 'Frame_CadAPI_OImpresso_Mestre.pas' {FrmOImpresso_Mestre: TFrame},
  Base_Boleto in 'Base_Boleto.pas' {FrmBoleto},
  Frame_ConBoleto in 'Frame_ConBoleto.pas' {Frame_ConsuBoleto: TFrame},
  Base_Credito in 'Base_Credito.pas' {FrmCredito},
  PDV_TipoNF_Selecao in 'PDV_TipoNF_Selecao.pas' {FrmPDV_TipoNF_Selecao},
  FundoTransparente in 'FundoTransparente.pas' {FundoTransparente},
  Base_Financeiro in 'Base_Financeiro.pas' {FrmFinanceiro_Base},
  Frame_CadBoleto in 'Frame_CadBoleto.pas' {Frame_Boleto: TFrame},
  Frame_ConCredito in 'Frame_ConCredito.pas' {Frame_ConsuCredito: TFrame},
  CadLancaCredito in 'CadLancaCredito.pas' {FrmLancaCredito},
  Frame_ConProdutoSubUnidade in 'Frame_ConProdutoSubUnidade.pas' {Frame_ConsuProdutoSubUnidade: TFrame},
  Base_ProdutoSubUnidade in 'Base_ProdutoSubUnidade.pas' {FrmProdutoSubUnidade},
  Frame_CadSubunidade in 'Frame_CadSubunidade.pas' {Frame_Subunidade: TFrame},
  Financeiro in '..\Geral\Contas\Financeiro.pas' {FrmFinanceiro},
  Base_Financeiro_Pocket in 'Base_Financeiro_Pocket.pas' {FrmFinanceiro_Pocket},
  Base_Conciliacao_Bancaria in 'Base_Conciliacao_Bancaria.pas' {FrmConciliacao_Bancaria},
  Frame_ConConciliacao_Bancaria in 'Frame_ConConciliacao_Bancaria.pas' {ConsuConciliacao_Bancaria: TFrame},
  Base_NotaFiscalEntrada in 'Base_NotaFiscalEntrada.pas' {FrmNotaFiscalEntrada},
  Base_Pessoas in 'Base_Pessoas.pas' {FrmPessoas},
  Frame_ConPessoas_OImpresso in 'Frame_ConPessoas_OImpresso.pas' {Frame_ConsuPessoas_OImpresso: TFrame},
  Frame_ConPessoas_Funcionario in 'Frame_ConPessoas_Funcionario.pas' {Frame_ConsuPessoas_Funcionario: TFrame},
  Frame_ConPessoas_Representante in 'Frame_ConPessoas_Representante.pas' {Frame_ConsuPessoas_Representante: TFrame},
  Frame_ConPessoas_Cliente in 'Frame_ConPessoas_Cliente.pas' {Frame_ConsuPessoas_Cliente: TFrame},
  Frame_ConPessoas_Fornecedor in 'Frame_ConPessoas_Fornecedor.pas' {Frame_ConsuPessoas_Fornecedor: TFrame},
  Frame_ConPessoas_Todos in 'Frame_ConPessoas_Todos.pas' {Frame_ConsuPessoas_Todos: TFrame},
  Frame_CadPessoas_Funcionario in 'Frame_CadPessoas_Funcionario.pas' {Frame_Pessoas_Funcionario},
  Frame_CadPessoas_Representante in 'Frame_CadPessoas_Representante.pas' {Frame_Pessoas_Representante: TFrame},
  Frame_CadPessoas_Cliente in 'Frame_CadPessoas_Cliente.pas' {Frame_Pessoas_Cliente: TFrame},
  Frame_CadPessoas_Fornecedor in 'Frame_CadPessoas_Fornecedor.pas' {Frame_Pessoas_Fornecedor: TFrame},
  Frame_CadPessoas_OImpresso in 'Frame_CadPessoas_OImpresso.pas' {Frame_Pessoas_OImpresso: TFrame},
  Frame_CadPessoas_Todos in 'Frame_CadPessoas_Todos.pas' {Frame_Pessoas_Todos: TFrame},
  Base_Pessoas_Modal in 'Base_Pessoas_Modal.pas' {FrmPessoas_Modal},
  Base_NotaFiscalEntrada_Pocket in 'Base_NotaFiscalEntrada_Pocket.pas' {FrmNotaFiscalEntrada_Pocket},
  Frame_CadNotaFiscalEntrada in 'Frame_CadNotaFiscalEntrada.pas' {Frame_NotaFiscalEntrada: TFrame},
  Base_Pocket_Mestre in 'Base_Pocket_Mestre.pas' {FrmBase_Pocket},
  Frame_Cad_Pocket in 'Frame_Cad_Pocket.pas' {FrmCad_Frame_Pocket: TFrame},
  Base_Venda in 'Base_Venda.pas' {FrmVenda_Base},
  Frame_ConVenda_Venda in 'Frame_ConVenda_Venda.pas' {Frame_ConsuVenda_Venda: TFrame},
  Frame_ConVenda_PDV in 'Frame_ConVenda_PDV.pas' {Frame_ConsuVenda_PDV: TFrame},
  Frame_ConVenda_Pedido in 'Frame_ConVenda_Pedido.pas' {Frame_ConsuVenda_Pedido: TFrame},
  Frame_ConVenda_Orcamento in 'Frame_ConVenda_Orcamento.pas' {Frame_ConsuVenda_Orcamento: TFrame},
  Frame_ConVenda_NotaFiscal in 'Frame_ConVenda_NotaFiscal.pas' {Frame_ConsuVenda_NotaFiscal: TFrame},
  Frame_ConVenda_OImpresso in 'Frame_ConVenda_OImpresso.pas' {Frame_ConsuVenda_OImpresso: TFrame},
  Frame_CadVenda_PDV in 'Frame_CadVenda_PDV.pas' {Frame_Venda_PDV: TFrame},
  Base_Comissao in 'Base_Comissao.pas' {FrmBaseComissao},
  Base_Comissao_Pocket in 'Base_Comissao_Pocket.pas' {FrmComissao_Pocket},
  Base_Venda_Modal in 'Base_Venda_Modal.pas' {FrmVenda_Modal},
  Frame_ConManifestacao_Historico in 'Frame_ConManifestacao_Historico.pas' {Consu_Frame1: TFrame},
  Frame_ConManifestacao_Eventos in 'Frame_ConManifestacao_Eventos.pas' {Frame_ConsuManifestacao_Eventos: TFrame},
  Base_TipoOcorrencia in '..\Aprocat\Base_TipoOcorrencia.pas' {FrmTipoOcorrencia},
  Base_Situacao in '..\Aprocat\Base_Situacao.pas' {FrmSituacao},
  Frame_CadPessoas_Associado in 'Frame_CadPessoas_Associado.pas' {Frame_Pessoas_Associado: TFrame},
  Frame_ConPessoas_Associado in 'Frame_ConPessoas_Associado.pas' {Frame_ConsuPessoas_Associado: TFrame},
  Base_TabelaFipe in '..\Aprocat\Base_TabelaFipe.pas' {FrmTabFipe},
  Frame_ConTabelaFipe in '..\Aprocat\Frame_ConTabelaFipe.pas' {ConsuTabelaFipe: TFrame},
  Frame_CadTabelaFipe in '..\Aprocat\Frame_CadTabelaFipe.pas' {Frame_TabelaFipe: TFrame},
  Base_Tabela_Valor in '..\Aprocat\Base_Tabela_Valor.pas' {FrmTabela_Valor},
  Frame_ConTabela_Valor in '..\Aprocat\Frame_ConTabela_Valor.pas' {Frame_ConsuTabela_Valor: TFrame},
  Base_TabelaFipe_Modal in '..\Aprocat\Base_TabelaFipe_Modal.pas' {FrmTabFipe_Modal},
  Base_Tabela_Valor_Modal in '..\Aprocat\Base_Tabela_Valor_Modal.pas' {FrmTabela_Valor_Modal},
  Base_TipoEquipamento_Modal in '..\Aprocat\Base_TipoEquipamento_Modal.pas' {FrmTipoEquipamentos_Modal},
  Base_Antifurto_Tipo in '..\Aprocat\Base_Antifurto_Tipo.pas' {FrmAntifurto_Tipo},
  Base_Antifurto_Tipo_Modal in '..\Aprocat\Base_Antifurto_Tipo_Modal.pas' {FrmAntifurto_Tipo_Modal},
  Base_TipoEquipamento in '..\Aprocat\Base_TipoEquipamento.pas' {FrmTipoEquipamentos},
  Base_Situacao_Modal in '..\Aprocat\Base_Situacao_Modal.pas' {FrmSituacao_Modal},
  Base_TipoOcorrencia_Modal in '..\Aprocat\Base_TipoOcorrencia_Modal.pas' {FrmBase_TipoOcorrencia_Modal},
  Base_Financeiro_Modal in 'Base_Financeiro_Modal.pas' {FrmFinanceiro_Modal},
  Frame_CadVenda_Orcamento in 'Frame_CadVenda_Orcamento.pas' {Frame_Venda_Orcamento: TFrame},
  Base_Equipamento in '..\Aprocat\Base_Equipamento.pas' {FrmEquipamento},
  Base_Equipamento_Modal in '..\Aprocat\Base_Equipamento_Modal.pas' {FrmEquipamento_Modal},
  Frame_ConEquipamento_Mestre in 'Frame_ConEquipamento_Mestre.pas' {ConsuEquipamento_Mestre: TFrame},
  Frame_ConEquipamento_Veiculo in 'Frame_ConEquipamento_Veiculo.pas' {ConsuEquipamento_Veiculo: TFrame},
  Frame_CadEquipamento_Veiculo in 'Frame_CadEquipamento_Veiculo.pas' {Frame_Equipamento_Veiculo: TFrame},
  Frame_ConEquipamento_Impressora in 'Frame_ConEquipamento_Impressora.pas' {ConsuEquipamento_Impressora: TFrame},
  Frame_CadEquipamento_Impressora in 'Frame_CadEquipamento_Impressora.pas' {Frame_Equipamento_Impressora: TFrame},
  Frame_ConEquipamento_Computador in 'Frame_ConEquipamento_Computador.pas' {ConsuEquipamento_Computador: TFrame},
  Frame_CadEquipamento_Computador in 'Frame_CadEquipamento_Computador.pas' {Frame_Equipamento_Computador: TFrame},
  Frame_ConEquipamento_Eletrodomestico in 'Frame_ConEquipamento_Eletrodomestico.pas' {ConsuEquipamento_Eletrodomestico: TFrame},
  Frame_CadEquipamento_Eletrodomestico in 'Frame_CadEquipamento_Eletrodomestico.pas' {Frame_Equipamento_Eletrodomestico: TFrame},
  Frame_ConAPI_OImpresso in 'Frame_ConAPI_OImpresso.pas' {Frame_ConsuAPI_OImpresso: TFrame},
  Base_API_OImpresso_Pocket in 'Base_API_OImpresso_Pocket.pas' {FrmAPI_OImpressao_Pocket},
  Frame_CadVenda_Pedido in 'Frame_CadVenda_Pedido.pas' {Frame_Venda_Pedido: TFrame},
  Frame_CadAPI_OImpresso_Configuracao in 'Frame_CadAPI_OImpresso_Configuracao.pas' {FrmOImpresso_Configuracao_Frame: TFrame},
  Base_Comissao_Selecao in 'Base_Comissao_Selecao.pas' {FrmComissao_Selecao},
  Frame_CadVenda_NotaFiscal in 'Frame_CadVenda_NotaFiscal.pas' {Frame_Venda_NotaFiscal: TFrame},
  Frame_ConComissao_Selecao_Financeiro in 'Frame_ConComissao_Selecao_Financeiro.pas' {Frame_ConsuComissao_Selecao_Financeiro: TFrame},
  Frame_ConEstoque_Requisicao in 'Frame_ConEstoque_Requisicao.pas' {ConsuEstoque_Requisicao: TFrame},
  Frame_ConComissao_Selecao_Venda in 'Frame_ConComissao_Selecao_Venda.pas' {Frame_ConsuComissao_Selecao_venda: TFrame},
  Base_Requisicao_Pocket in 'Base_Requisicao_Pocket.pas' {FrmRequisicao_Pocket},
  Base_Comissao_Selecao_Modal in 'Base_Comissao_Selecao_Modal.pas' {FrmComissao_Selecao_Modal},
  Frame_CadRequisicao_Pocket in 'Frame_CadRequisicao_Pocket.pas' {Frame_Requisicao_Pocket: TFrame},
  Frame_OImpresso_Pessoas in 'Frame_OImpresso_Pessoas.pas' {FrmOImpresso_Pessoas: TFrame},
  FrmBaixa_Requisicao in 'FrmBaixa_Requisicao.pas' {FormBaixa_Requisicao},
  Frame_ConComissao_Selecao_Financeiro_Agencia in 'Frame_ConComissao_Selecao_Financeiro_Agencia.pas' {Frame_ConsuComissao_Selecao_Financeiro_Agencia: TFrame},
  Base_Requisicao_Motivo in 'Base_Requisicao_Motivo.pas' {FrmBaseRequisicao_Motivo},
  Frame_ConComissao_Selecao_Financeiro_Funcionario in 'Frame_ConComissao_Selecao_Financeiro_Funcionario.pas' {Frame_ConsuComissao_Selecao_Financeiro_Funcionario: TFrame},
  Frame_CadRequisicao_Motivo in 'Frame_CadRequisicao_Motivo.pas' {Frame_Requisicao_Motivo: TFrame},
  Frame_ConComissao_Selecao_Financeiro_Representante in 'Frame_ConComissao_Selecao_Financeiro_Representante.pas' {Frame_ConsuComissao_Selecao_Financeiro_Representante: TFrame},
  Frame_ConRequisicao_Motivo in 'Frame_ConRequisicao_Motivo.pas' {ConsuRequisicao_Motivo: TFrame},
  Base_Cor in 'Base_Cor.pas' {FrmCor},
  Base_Cor_Modal in 'Base_Cor_Modal.pas' {FrmCor_Modal},
  frFrame_Producao_Fluxo in 'frFrame_Producao_Fluxo.pas' {Frame_Producao_Fluxo: TFrame},
  Frame_Producao_Fluxo_Produto in 'Frame_Producao_Fluxo_Produto.pas' {FrmFrame_Producao_Fluxo_Produto: TFrame},
  Frame_ConEstoque_Estoque in 'Frame_ConEstoque_Estoque.pas' {Frame_ConsuEstoque_Estoque: TFrame},
  Frame_ConRelVenda_Produto in 'Frame_ConRelVenda_Produto.pas' {Frame_ConsuRelVenda_Produto: TFrame},
  Frame_Producao_Fluxo_Venda_Produto in 'Frame_Producao_Fluxo_Venda_Produto.pas' {FrmFrame_Producao_Fluxo_Venda_Produto: TFrame},
  Base_SLA in 'Base_SLA.pas' {FrmNotificacao},
  Frame_CadSLA in 'Frame_CadSLA.pas' {Frame_Notificacao: TFrame},
  Frame_ConSLA in 'Frame_ConSLA.pas' {ConsuNotificacao: TFrame},
  Base_SLA_Pocket in 'Base_SLA_Pocket.pas' {FrmNotificacao_Pocket},
  wrSLA in 'wrSLA.pas',
  Controller.KPI in 'app\Controller\Controller.KPI.pas',
  wrMenu in 'wrMenu.pas',
  ConNotificacao_Disparada in 'ConNotificacao_Disparada.pas' {ConsuNotificacao_Disparada: TFrame},
  frFrameHistorico_SLA in 'frFrameHistorico_SLA.pas' {FrameHistorico_SLA: TFrame},
  Base_APP in 'Base_APP.pas' {FrmAPP},
  Sugestoes in 'Sugestoes.pas' {FrmSugestoes},
  wrSugestoes in 'wrSugestoes.pas',
  Frame_APP in 'Frame_APP.pas' {FrameApp: TFrame},
  Base_Configuracao_Cronjob in 'Base_Configuracao_Cronjob.pas' {FrmConfiguracao_CronJob},
  Frame_ConConfiguracao_Cronjob in 'Frame_ConConfiguracao_Cronjob.pas' {ConsuConfiguracao_Cronjob: TFrame},
  Base_APP_Menu in 'Base_APP_Menu.pas' {Menu_Mestre},
  Frame_OImpresso_Produtos in 'Frame_OImpresso_Produtos.pas' {FrmOImpresso_Produtos: TFrame},
  Base_BI in 'Base_BI.pas' {FrmBase_BI},
  Frame_BI_Acoes in 'Frame_BI_Acoes.pas' {FrmFrame_BI_Acoes: TFrame},
  Frame_BI_Permissoes in 'Frame_BI_Permissoes.pas' {FrmFrame_BI_Permissoes: TFrame},
  Base_BI_KPI in 'Base_BI_KPI.pas' {BaseBI_KPI},
  Frame_PainelBI_Associacao in 'Frame_PainelBI_Associacao.pas' {FrameBI_Associacao: TFrame},
  Frame_PainelBI_Compras in 'Frame_PainelBI_Compras.pas' {FrameBI_Compras: TFrame},
  Frame_PainelBI_Configuracoes in 'Frame_PainelBI_Configuracoes.pas' {FrameBI_Configuracoes: TFrame},
  Frame_PainelBI_Estoque in 'Frame_PainelBI_Estoque.pas' {FrameBI_Estoque: TFrame},
  Frame_PainelBI_Faturamento in 'Frame_PainelBI_Faturamento.pas' {FrameBI_Faturamento: TFrame},
  Frame_PainelBI_Financeiro in 'Frame_PainelBI_Financeiro.pas' {FrameBI_Financeiro: TFrame},
  Frame_PainelBI_Producao in 'Frame_PainelBI_Producao.pas' {FrameBI_Producao: TFrame},
  Frame_PainelBI_RH in 'Frame_PainelBI_RH.pas' {FrameBI_RH: TFrame},
  Frame_PainelBI_Vendas in 'Frame_PainelBI_Vendas.pas' {FrameBI_Vendas: TFrame},
  Frame_ConFinanceiro_Centro_Custo_Mestre in 'Frame_ConFinanceiro_Centro_Custo_Mestre.pas' {Frame_ConsuFinanceiro_Centro_Custo_Mestre: TFrame},
  Frame_ConFinanceiro_Financeiro in '..\Geral\Contas\Frame_ConFinanceiro_Financeiro.pas' {Frame_ConsuFinanceiro_Financeiro: TFrame},
  Base_Producao in 'Base_Producao.pas' {bFrmProducao},
  Configuracao_Valor in 'Configuracao_Valor.pas' {FrmConfiguracao_Valor},
  Frame_Acao_Configuracao in 'Frame_Acao_Configuracao.pas' {FrmFrame_Acao_Configuracao: TFrame},
  Frame_CadContrato in 'Frame_CadContrato.pas' {FrameCadContrato: TFrame},
  Frame_ConContrato in 'Frame_ConContrato.pas' {FrameConContrato: TFrame},
  Base_Comunicacao in 'Base_Comunicacao.pas' {FrmComunicacao},
  Base_Arquivos_Relatorio in 'Base_Arquivos_Relatorio.pas' {FrmArquivos_Relatorio1},
  Base_Arquivos_Relatorio_Normal in 'Base_Arquivos_Relatorio_Normal.pas' {FrmArquivos_Relatorio_Normal},
  Base_Lista_Corte in 'Base_Lista_Corte.pas' {FrmLista_Corte},
  Frame_ConLista_Corte in 'Frame_ConLista_Corte.pas' {ConsuLista_Corte: TFrame},
  Classes.Acoes in 'app\Classes\Classes.Acoes.pas',
  Frame_ConEstoque_Produto_Movimento in 'Frame_ConEstoque_Produto_Movimento.pas' {Frame_ConsuEstoque_Produto_Movimento: TFrame},
  Base_RelVenda_Produto in 'Base_RelVenda_Produto.pas' {FrmRelVenda_Produtoo},
  Base_NF_Entrada_Produto in 'Base_NF_Entrada_Produto.pas' {FrmRelNF_Entrada_Produto},
  Frame_Painel_CentroCusto_Categoria in 'Frame_Painel_CentroCusto_Categoria.pas' {Painel_CentroCusto_Categoria: TFrame},
  Base_Plano_Contas in 'Base_Plano_Contas.pas' {BasePlanoContas},
  Base_Plano_Contas_Modal in 'Base_Plano_Contas_Modal.pas' {FrmPlanoContas_Modal},
  Base_Ficha_Ponto in 'Base_Ficha_Ponto.pas' {FrmFicha_ponto},
  Frame_ConPessoas_Ficha_Ponto in 'Frame_ConPessoas_Ficha_Ponto.pas' {Frame_ConsuPessoas_Funcionario_Ficha_Ponto: TFrame},
  Frame_CadPessoas_Funcionario_Ficha_Ponto in 'Frame_CadPessoas_Funcionario_Ficha_Ponto.pas' {Frame_Pessoas_Funcionario_Ficha_Ponto: TFrame},
  Base_Centro_Custo_Pocket in 'Base_Centro_Custo_Pocket.pas' {FrmCentro_Custo_Pocket},
  Frame_CadFinanceiro_Centro_Custo_Mestre in 'Frame_CadFinanceiro_Centro_Custo_Mestre.pas' {Frame_Financeiro_Centro_Custo_Mestre: TFrame},
  Frame_ConFinanceiro_Centro_Custo_Produto_Categoria in 'Frame_ConFinanceiro_Centro_Custo_Produto_Categoria.pas' {Frame_ConsuFinanceiro_Centro_Custo_Produto_Categoria: TFrame},
  Frame_CadFinanceiro_Centro_Custo_Produto_Categoria in 'Frame_CadFinanceiro_Centro_Custo_Produto_Categoria.pas' {Frame_Financeiro_Centro_Custo_Produto_Categoria: TFrame},
  Base_DRE in 'Base_DRE.pas' {BaseDRE},
  Routes.API in 'app\routes\Routes.API.pas',
  Frame_ConDRE in 'Frame_ConDRE.pas' {ConsuConDRE: TFrame},
  Controller_Producao in 'app\Controller\Controller_Producao.pas',
  Controller_Venda in 'app\Controller\Controller_Venda.pas',
  Controller.API in 'app\Controller\Controller.API.pas',
  Frame_ConProducao_Planejamento in 'Frame_ConProducao_Planejamento.pas' {Frame_Consuproducao_Planejamento: TFrame},
  Frame_ConProducao_Tarefas in 'Frame_ConProducao_Tarefas.pas' {Frame_ConsuProducao_Tarefas: TFrame},
  Frame_ConProducao_Agenda in 'Frame_ConProducao_Agenda.pas' {Frame_Consuproducao_Agenda: TFrame},
  Frame_ConProducao_Kanban in 'Frame_ConProducao_Kanban.pas' {Frame_ConsuProducao_Kanban: TFrame},
  wr_memoria in 'wr_memoria.pas',
  Base_Producao_pocket in 'Base_Producao_pocket.pas' {FrmBase_Producao_Pocket},
  VerificaDiretorioThread in 'VerificaDiretorioThread.pas',
  Frame_Cad in '..\Geral\Frame_Cad.pas' {FrmCad_Frame: TFrame},
  Frame_ConBalanco_Patrimonial_Classificacao in 'Frame_ConBalanco_Patrimonial_Classificacao.pas' {Frame_ConsuBalanco_Patrimonial_Classificacao: TFrame},
  Base_Balanco_Patrimonial_Classificacao in 'Base_Balanco_Patrimonial_Classificacao.pas' {FrmBalanco_Patr_Classificacao},
  Frame_CadBalanco_Patrimonial_Classificacao in 'Frame_CadBalanco_Patrimonial_Classificacao.pas' {Frame_Balanco_Patr_Classificacao: TFrame},
  Base_Balanco_Patrimonial_Classificacao_Modal in 'Base_Balanco_Patrimonial_Classificacao_Modal.pas' {FrmBalanco_Patr_Classificacao_Modal},
  Base_DRE_Classificacao in 'Base_DRE_Classificacao.pas' {FrmBase1},
  Base_BI_Geral in 'Base_BI_Geral.pas' {FrmBase_BI_Geral},
  Base_Salario in 'Base_Salario.pas' {FrmSalario},
  Frame_CadSalario in 'Frame_CadSalario.pas' {Frame_Salario: TFrame},
  Frame_ConSalario in 'Frame_ConSalario.pas' {ConsuSalario: TFrame},
  Frame_ConPrecificacao in 'Frame_ConPrecificacao.pas' {ConsuPrecificacao: TFrame},
  Base_Precificacao in 'Base_Precificacao.pas' {FrmRateio_Custo},
  Frame_CadPrecificacao in 'Frame_CadPrecificacao.pas' {FrmPrecificacao: TFrame},
  frFrameEncargos in 'frFrameEncargos.pas' {Frame_Encargos},
  frmConferencia_Compra in 'frmConferencia_Compra.pas' {FormConferencia_Compra},
  CadFolha_Pagamento in '..\Geral\Contas\CadFolha_Pagamento.pas' {FrmFolha_Pagamento},
  FrFrame_Rateio_Equipe in 'FrFrame_Rateio_Equipe.pas' {Frame_Rateio_Equipe},
  FrFrame_Rateio_Custo_Vinculo in 'FrFrame_Rateio_Custo_Vinculo.pas' {Frame_Rateio_Custo_Vinculo},
  FrFrame_Rateio_Custo_Vinculo_Equipe in 'FrFrame_Rateio_Custo_Vinculo_Equipe.pas' {Frame_Rateio_Custo_Vinculo_Equipe},
  Frame_CadProduto_Venda in 'Frame_CadProduto_Venda.pas' {Frame_Produto_Venda: TFrame},
  Frame_CadProducao_Rateio in 'Frame_CadProducao_Rateio.pas' {FrameProducao_Rateio: TFrame},
  Base_Producao_Rateio in 'Base_Producao_Rateio.pas' {FrmProducao_Rateio},
  Frame_ConProducao_Rateio in 'Frame_ConProducao_Rateio.pas' {ConsuProducao_Rateio: TFrame},
  FrFrameComposicao_Variacao in 'FrFrameComposicao_Variacao.pas' {FrmFrameComposicao_Variacao: TFrame},
  frFrameSelecionarVariacao in 'frFrameSelecionarVariacao.pas' {Frame_Selecionar_Variacao},
  FrmProdutoGradePanel in 'FrmProdutoGradePanel.pas' {FrmProdutoGradePanel},
  SQL.Produto_Requisicao in 'app\SQL\SQL.Produto_Requisicao.pas',
  SQL.Pessoas in 'app\SQL\SQL.Pessoas.pas',
  SQL.Compra in 'app\SQL\SQL.Compra.pas',
  SQL.Contas in 'app\SQL\SQL.Contas.pas',
  SQL.Boleto in 'app\SQL\SQL.Boleto.pas',
  SQL.Financeiro in 'app\SQL\SQL.Financeiro.pas',
  SQL.Financeiro_Boleto in 'app\SQL\SQL.Financeiro_Boleto.pas',
  SQL.Financeiro_Boleto_Historico in 'app\SQL\SQL.Financeiro_Boleto_Historico.pas',
  Utils.Boleto in 'app\Utils\Boleto\Utils.Boleto.pas',
  Utils.Boleto.Retorno in 'app\Utils\Boleto\Utils.Boleto.Retorno.pas',
  Utils.Empresa in 'app\Utils\Utils.Empresa.pas',
  Utils.Requisicao.Compra in 'app\Utils\Requisicao\Utils.Requisicao.Compra.pas',
  Utils.Requisicao.Venda in 'app\Utils\Requisicao\Utils.Requisicao.Venda.pas',
  Utils.Requisicao in 'app\Utils\Requisicao\Utils.Requisicao.pas',
  Utils.Produto.Variacao in 'app\Utils\Utils.Produto.Variacao.pas',
  Utils.Produto in 'app\Utils\Produto\Utils.Produto.pas',
  Routes in 'app\routes\Routes.pas',
  Routes.Mestre in 'app\routes\Routes.Mestre.pas',
  Routes.Financeiro in 'app\routes\Routes.Financeiro.pas',
  Routes.Produto in 'app\routes\Routes.Produto.pas',
  Routes.Produto.Variacao in 'app\routes\Routes.Produto.Variacao.pas',
  Routes.Requisicao.Compra in 'app\routes\Routes.Requisicao.Compra.pas',
  Routes.Requisicao.Venda in 'app\routes\Routes.Requisicao.Venda.pas',
  Routes.Requisicao.Estoque in 'app\routes\Routes.Requisicao.Estoque.pas',
  Controller.Venda in 'app\Controller\Controller.Venda.pas',
  Controller.Mestre in 'app\Controller\Controller.Mestre.pas',
  Controller.Requisicao in 'app\Controller\Controller.Requisicao.pas',
  Controller.Requisicao.Venda in 'app\Controller\Controller.Requisicao.Venda.pas',
  Controller.Requisicao.Compra in 'app\Controller\Controller.Requisicao.Compra.pas',
  Controller.Requisicao.Producao in 'app\Controller\Controller.Requisicao.Producao.pas',
  Controller.Requisicao.Estoque in 'app\Controller\Controller.Requisicao.Estoque.pas',
  Controller.Produto in 'app\Controller\Controller.Produto.pas',
  Controller.Produto.Variacao in 'app\Controller\Controller.Produto.Variacao.pas',
  Controller.Compra in 'app\Controller\Controller.Compra.pas',
  Controller.Compra.Estoque in 'app\Controller\Controller.Compra.Estoque.pas',
  Controller.Contas in 'app\Controller\Controller.Contas.pas',
  Controller.Financeiro in 'app\Controller\Controller.Financeiro.pas',
  Controller.Boleto in 'app\Controller\Controller.Boleto.pas',
  Controller.Contrato in 'app\Controller\Controller.Contrato.pas',
  Controller.Interno.Venda in 'app\Controller.Interno\Controller.Interno.Venda.pas',
  Controller.WR_Config in 'app\Controller\Controller.WR_Config.pas',
  Controller.WR_Obrigatorio in 'app\Controller\Controller.WR_Obrigatorio.pas',
  Controller.WR_Valor_Inicial in 'app\Controller\Controller.WR_Valor_Inicial.pas',
  Controller.WR_Componente in 'app\Controller\Controller.WR_Componente.pas',
  Controller.Financeiro_Centro_Custo in 'app\Controller\Controller.Financeiro_Centro_Custo.pas',
  Controller.Interno.Financeiro_Centro_Custo in 'app\Controller.Interno\Controller.Interno.Financeiro_Centro_Custo.pas',
  Services.Mestre in 'app\Services\Services.Mestre.pas',
  Services.Produto in 'app\Services\Services.Produto.pas',
  Services.Produto.Variacao in 'app\Services\Services.Produto.Variacao.pas',
  Services.Requisicao in 'app\Services\Services.Requisicao.pas',
  Services.Venda in 'app\Services\Services.Venda.pas',
  Services.Estoque in 'app\Services\Services.Estoque.pas',
  Services.Compra in 'app\Services\Services.Compra.pas',
  Services.Financeiro in 'app\Services\Services.Financeiro.pas',
  Relatorios.Venda in 'app\Relatorios\Relatorios.Venda.pas',
  Services.Boleto in 'app\Services\Services.Boleto.pas',
  Services.Boleto.WS in 'app\Services\Services.Boleto.WS.pas',
  Services.Financeiro_Centro_Custo in 'app\Services\Services.Financeiro_Centro_Custo.pas',
  SQL.Financeiro_Centro_Custo in 'app\SQL\SQL.Financeiro_Centro_Custo.pas',
  Utils.Financeiro_Centro_Custo in 'app\Utils\Utils.Financeiro_Centro_Custo.pas',
  FrmDataCentroCusto in 'FrmDataCentroCusto.pas' {FormDataCentroCusto},
  Classes.Financeiro in 'app\Classes\Classes.Financeiro.pas',
  Classes.PlanoContas in 'app\Classes\Classes.PlanoContas.pas',
  SQL.PlanoContas in 'app\SQL\SQL.PlanoContas.pas',
  SQL.Venda in 'app\SQL\SQL.Venda.pas',
  SQL.Arquivo_Relatorio in 'app\SQL\SQL.Arquivo_Relatorio.pas',
  WRButtonsEditAdd in '..\Componentes\WRButtonsEditAdd.pas',
  SQL.WR_Componente in 'app\SQL\SQL.WR_Componente.pas',
  SQL.WR_Valor_Inicial in 'app\SQL\SQL.WR_Valor_Inicial.pas',
  SQL.WR_Form in 'app\SQL\SQL.WR_Form.pas',
  Controller.WR_Form in 'app\Controller\Controller.WR_Form.pas',
  SQL.WR_Agrupador in 'app\SQL\SQL.WR_Agrupador.pas',
  Controller.WR_Agrupador in 'app\Controller\Controller.WR_Agrupador.pas',
  Controller.WR_Filtro in 'app\Controller\Controller.WR_Filtro.pas',
  SQL.WR_Filtro in 'app\SQL\SQL.WR_Filtro.pas',
  wr.Modulo in 'app\WR\wr.Modulo.pas',
  wr.APP.Venda in 'app\WR\APP\wr.APP.Venda.pas',
  wr.Config in 'app\WR\Config\wr.Config.pas',
  wr.Componente.Venda in 'app\WR\Componente\wr.Componente.Venda.pas',
  wr.Form in 'app\WR\wr.Form.pas',
  wr.Valor_Inicial in 'app\WR\Valor_Inicial\wr.Valor_Inicial.pas',
  wr.Estilo in 'app\WR\Estilo\wr.Estilo.pas',
  SQL.WR_Config in 'app\SQL\SQL.WR_Config.pas',
  SQL.WR_Obrigatorio in 'app\SQL\SQL.WR_Obrigatorio.pas',
  wr.Config.Financeiro in 'app\WR\Config\wr.Config.Financeiro.pas',
  wr.Config.Associacao in 'app\WR\Config\wr.Config.Associacao.pas',
  wr.Config.Venda in 'app\WR\Config\wr.Config.Venda.pas',
  wr.Config.Compra in 'app\WR\Config\wr.Config.Compra.pas',
  wr.Config.Compra.ImportarXML in 'app\WR\Config\wr.Config.Compra.ImportarXML.pas',
  wr.Config.Financeiro_Caixa in 'app\WR\Config\wr.Config.Financeiro_Caixa.pas',
  wr.Config.Venda.TabelaDePreco in 'app\WR\Config\wr.Config.Venda.TabelaDePreco.pas',
  wr.Config.Venda.Pedido in 'app\WR\Config\wr.Config.Venda.Pedido.pas',
  wr.Config.Produto.Estoque in 'app\WR\Config\wr.Config.Produto.Estoque.pas',
  wr.Config.Produto.Estoque.Armazem in 'app\WR\Config\wr.Config.Produto.Estoque.Armazem.pas',
  wr.Config.Produto.Markup in 'app\WR\Config\wr.Config.Produto.Markup.pas',
  wr.Config.Associacao.Rateio in 'app\WR\Config\wr.Config.Associacao.Rateio.pas',
  wr.Config.Associacao.Ocorrencia in 'app\WR\Config\wr.Config.Associacao.Ocorrencia.pas',
  wr.Config.Venda.Proposta in 'app\WR\Config\wr.Config.Venda.Proposta.pas',
  wr.Config.Produto.Variacao in 'app\WR\Config\wr.Config.Produto.Variacao.pas',
  wr.Config.Produto.SubUnidade in 'app\WR\Config\wr.Config.Produto.SubUnidade.pas',
  wr.Config.Produto.Composicao in 'app\WR\Config\wr.Config.Produto.Composicao.pas',
  wr.Config.Produto.Codigo_Barras in 'app\WR\Config\wr.Config.Produto.Codigo_Barras.pas',
  wr.Config.FichaPonto in 'app\WR\Config\wr.Config.FichaPonto.pas',
  wr.Config.CRM.Agendamento in 'app\WR\Config\wr.Config.CRM.Agendamento.pas',
  wr.Obrigatorio.Venda.NFe in 'app\WR\Obrigatorio\wr.Obrigatorio.Venda.NFe.pas',
  wr.Obrigatorio.Venda.NFe.Devolucao in 'app\WR\Obrigatorio\wr.Obrigatorio.Venda.NFe.Devolucao.pas',
  wr.Agrupador.Pessoas in 'app\WR\Agrupador\wr.Agrupador.Pessoas.pas',
  wr.Agrupador.Comissao in 'app\WR\Agrupador\wr.Agrupador.Comissao.pas',
  Tag.APP in 'app\Tag\Tag.APP.pas',
  Tag.Agrupador in 'app\Tag\Tag.Agrupador.pas',
  Tag.Componente in 'app\Tag\Tag.Componente.pas',
  Tag.Valor_Inicial in 'app\Tag\Tag.Valor_Inicial.pas',
  Base in '..\Geral\Base.pas' {FrmBase},
  Tag.KPI in 'app\Tag\Tag.KPI.pas',
  Tag.Filtro in 'app\Tag\Tag.Filtro.pas',
  Tag.Report in 'app\Tag\Tag.Report.pas',
  Tag.Config in 'app\Tag\Tag.Config.pas',
  wr.Config.Link.Venda in 'app\WR\Config.Link\wr.Config.Link.Venda.pas',
  wr.APP.Estoque in 'app\WR\APP\wr.APP.Estoque.pas',
  wr.APP.Producao in 'app\WR\APP\wr.APP.Producao.pas',
  wr.APP.Financeiro in 'app\WR\APP\wr.APP.Financeiro.pas',
  wr.APP.Compra in 'app\WR\APP\wr.APP.Compra.pas',
  wr.APP.BI in 'app\WR\APP\wr.APP.BI.pas',
  wr.APP.Associacao in 'app\WR\APP\wr.APP.Associacao.pas',
  wr.APP.Integracoes in 'app\WR\APP\wr.APP.Integracoes.pas',
  wr.APP.Faturamento in 'app\WR\APP\wr.APP.Faturamento.pas',
  wr.APP.Produtividade in 'app\WR\APP\wr.APP.Produtividade.pas',
  wr.APP.RH in 'app\WR\APP\wr.APP.RH.pas',
  wr.APP.Documento in 'app\WR\APP\wr.APP.Documento.pas',
  wr.APP.Relatorio in 'app\WR\APP\wr.APP.Relatorio.pas',
  wr.Permissao.Venda in 'app\WR\Permissao\wr.Permissao.Venda.pas',
  wr.Campo.ConfigAdcional in 'app\WR\Campo.ConfigAdicional\wr.Campo.ConfigAdcional.pas',
  Controller.Principal in 'app\Controller\Controller.Principal.pas',
  wr.APP.CRM in 'app\WR\APP\wr.APP.CRM.pas',
  Tag.WREventosCadastro in 'app\Tag\Tag.WREventosCadastro.pas',
  Tag.Cache in 'app\Tag\Tag.Cache.pas',
  Controller.Obrigatorio.Venda.Venda in 'app\Controller.Obrigatorio\Controller.Obrigatorio.Venda.Venda.pas',
  Venda.Venda in 'app\Venda.Venda.pas',
  _Mestre in 'app\_Mestre.pas',
  Classes.Pointer_WREventosCadastro in 'app\Classes\Classes.Pointer_WREventosCadastro.pas',
  Classes.Boletos in 'app\Classes\Classes.Boletos.pas',
  Boleto.WS.Sicredi.Test in 'Testes\Boleto\WS\Boleto.WS.Sicredi.Test.pas',
  Boleto.WS.Santander.Test in 'Testes\Boleto\WS\Boleto.WS.Santander.Test.pas',
  Boleto.WS.PenseBank.Test in 'Testes\Boleto\WS\Boleto.WS.PenseBank.Test.pas',
  Boleto.WS.Credisis.Test in 'Testes\Boleto\WS\Boleto.WS.Credisis.Test.pas',
  Boleto.WS.Caixa.Test in 'Testes\Boleto\WS\Boleto.WS.Caixa.Test.pas',
  Boleto.WS.Bancoob.Test in 'Testes\Boleto\WS\Boleto.WS.Bancoob.Test.pas',
  Boleto.WS.BancoBrasil.Test in 'Testes\Boleto\WS\Boleto.WS.BancoBrasil.Test.pas',
  ACBrTests.Util in 'Testes\ACBrTests.Util.pas',
  ACBrTests.Runner in 'Testes\ACBrTests.Runner.pas',
  Boleto.Arquivo.BancoBrasil.Test in 'Testes\Boleto\Arquivo\Boleto.Arquivo.BancoBrasil.Test.pas',
  Boleto.Arquivo.Bancoob.Test in 'Testes\Boleto\Arquivo\Boleto.Arquivo.Bancoob.Test.pas',
  Boleto.Arquivo.Caixa.Test in 'Testes\Boleto\Arquivo\Boleto.Arquivo.Caixa.Test.pas',
  Boleto.Arquivo.Credisis.Test in 'Testes\Boleto\Arquivo\Boleto.Arquivo.Credisis.Test.pas',
  Boleto.Arquivo.PenseBank.Test in 'Testes\Boleto\Arquivo\Boleto.Arquivo.PenseBank.Test.pas',
  Boleto.Arquivo.Santander.Test in 'Testes\Boleto\Arquivo\Boleto.Arquivo.Santander.Test.pas',
  Boleto.Arquivo.Sicredi.Test in 'Testes\Boleto\Arquivo\Boleto.Arquivo.Sicredi.Test.pas',
  ACBrBoletoTest.BB in 'Testes\Boleto\ACBrBoletoTest.BB.pas',
  ACBrBoletoTest.Bradesco in 'Testes\Boleto\ACBrBoletoTest.Bradesco.pas',
  ACBrBoletoTest.Caixa in 'Testes\Boleto\ACBrBoletoTest.Caixa.pas',
  ACBrBoletoTest.Itau in 'Testes\Boleto\ACBrBoletoTest.Itau.pas',
  ACBrBoletoTest.Santander in 'Testes\Boleto\ACBrBoletoTest.Santander.pas',
  ACBrBoletoTest.Unicred in 'Testes\Boleto\ACBrBoletoTest.Unicred.pas',
  ACBrBoletoTest.UnicredES in 'Testes\Boleto\ACBrBoletoTest.UnicredES.pas',
  ACBrBoletoTest.Util in 'Testes\Boleto\ACBrBoletoTest.Util.pas',
  SQL.Cidades in 'app\SQL\SQL.Cidades.pas',
  Services.Cidades in 'app\Services\Services.Cidades.pas',
  Controller.Cidades in 'app\Controller\Controller.Cidades.pas',
  Routes.Pessoas in 'app\routes\Routes.Pessoas.pas',
  Services.Pessoas in 'app\Services\Services.Pessoas.pas',
  Services.Contas in 'app\Services\Services.Contas.pas',
  Routes.Contas in 'app\routes\Routes.Contas.pas',
  Controller.Pessoas in 'app\Controller\Controller.Pessoas.pas',
  SQL.Bancos in 'app\SQL\SQL.Bancos.pas',
  Relatorios.Balanco in 'app\Relatorios\Relatorios.Balanco.pas',
  Routes.Financeiro.Contas in 'app\routes\Routes.Financeiro.Contas.pas',
  Routes.Financeiro.Venda in 'app\routes\Routes.Financeiro.Venda.pas',
  Routes.Financeiro.Credito in 'app\routes\Routes.Financeiro.Credito.pas',
  Controller.Interno.Boleto.Arquivo in 'app\Controller.Interno\Boleto\Arquivo\Controller.Interno.Boleto.Arquivo.pas',
  Controller.Interno.Contas in 'app\Controller.Interno\Controller.Interno.Contas.pas',
  Controller.Interno.Boleto.Testes in 'app\Controller.Interno\Boleto\Controller.Interno.Boleto.Testes.pas',
  Controller.Interno.Boleto.Financeiro in 'app\Controller.Interno\Boleto\Controller.Interno.Boleto.Financeiro.pas',
  Controller.Interno.Boleto.WS in 'app\Controller.Interno\Boleto\WS\Controller.Interno.Boleto.WS.pas',
  Services.Boleto.Arquivo in 'app\Services\Services.Boleto.Arquivo.pas',
  Services.Interno.Boleto.Arquivo in 'app\Services.Interno\Services.Interno.Boleto.Arquivo.pas',
  Relatorios.Barras in 'app\Relatorios\Relatorios.Barras.pas',
  Base_WR_Controle in 'Base_WR_Controle.pas' {FrmWR_Controle},
  Frame_ConWR_Controle in 'Frame_ConWR_Controle.pas' {ConsuWR_Controle: TFrame},
  Frame_CadWR_Controle in 'Frame_CadWR_Controle.pas' {Frame_WR_Controle: TFrame},
  Relatorios.Financeiro in 'app\Relatorios\Relatorios.Financeiro.pas',
  Controller.Historico_Editando in 'app\Controller\Controller.Historico_Editando.pas',
  SQL.WR_Controle in 'app\SQL\SQL.WR_Controle.pas',
  SQL.WR_APP in 'app\SQL\SQL.WR_APP.pas',
  SQL.WR_Modulo in 'app\SQL\SQL.WR_Modulo.pas',
  Controller.WR_Modulo in 'app\Controller\Controller.WR_Modulo.pas',
  Controller.WR_APP in 'app\Controller\Controller.WR_APP.pas',
  Tag.Modulo in 'app\Tag\Tag.Modulo.pas',
  wr.Relatorio in 'app\WR\Relatorio\wr.Relatorio.pas',
  SQL.WR_Controle_Parent in 'app\SQL\SQL.WR_Controle_Parent.pas',
  Controller.WR_Controle in 'app\Controller\Controller.WR_Controle.pas',
  wr.Filtro in 'app\WR\Filtro\wr.Filtro.pas',
  wr.Filtro.Venda in 'app\WR\Filtro\wr.Filtro.Venda.pas',
  wr.KPI in 'app\WR\KPI\wr.KPI.pas',
  Tag.Obrigatorio in 'app\Tag\Tag.Obrigatorio.pas',
  wr.Obrigatorio in 'app\WR\Obrigatorio\wr.Obrigatorio.pas',
  Controller.Obrigatorio.NFe in 'app\Controller.Obrigatorio\Controller.Obrigatorio.NFe.pas',
  wr.Obrigatorio.Venda.NFCe in 'app\WR\Obrigatorio\wr.Obrigatorio.Venda.NFCe.pas',
  wr.Obrigatorio.Venda.NFSe in 'app\WR\Obrigatorio\wr.Obrigatorio.Venda.NFSe.pas',
  Tag.Condicao in 'app\Tag\Tag.Condicao.pas',
  Controller.WR_Condicao in 'app\Controller\Controller.WR_Condicao.pas',
  Tag.Permissao in 'app\Tag\Tag.Permissao.pas',
  Controller.WR_Permissao in 'app\Controller\Controller.WR_Permissao.pas',
  SQL.WR_Condicao in 'app\SQL\SQL.WR_Condicao.pas',
  wr.Condicao in 'app\WR\Condicao\wr.Condicao.pas',
  SQL.WR_Permissao in 'app\SQL\SQL.WR_Permissao.pas',
  wr.Permissao in 'app\WR\Permissao\wr.Permissao.pas',
  wr.Obrigatorio.Venda.Financeiro in 'app\WR\Obrigatorio\wr.Obrigatorio.Venda.Financeiro.pas',
  Tag.Form in 'app\Tag\Tag.Form.pas',
  Base_WR_Controle_Modal in 'Base_WR_Controle_Modal.pas' {FrmWR_Controle_Modal},
  Base_WR_Controle_Pocket in 'Base_WR_Controle_Pocket.pas' {FrmWR_Controle_Pocket},
  wr.Agrupador in 'app\WR\Agrupador\wr.Agrupador.pas',
  Frame_CadVenda_Projeto in 'Frame_CadVenda_Projeto.pas' {Frame_Venda_Projeto: TFrame},
  Frame_ConVenda_Projeto in 'Frame_ConVenda_Projeto.pas' {Frame_ConsuVenda_Projeto: TFrame},
  FrmWR_Kanbam in 'FrmWR_Kanbam.pas' {FormWR_Kanbam},
  Base_VendaNormal in 'Base_VendaNormal.pas' {FrmVenda_BaseNormal};

// não pode criar se for ser usado em um único lugar

{$R *.res}
{$R Languages.res} //Arquivo de idiomas, necessário para os componentes do DevExpress

begin
  {.$DEFINE PAFNFE}
  ApplicationTitle := 'Office Comercial';  //Não alterar esta linha!!!!
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  PAFNFE := False ;
  FrmSplash := TFrmSplash.Create(nil);
  try
    if PAFNFE then
      Application.ShowMainForm := False
    else
      FrmSplash.Show;
    Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  finally
    FrmSplash.Free;
    FrmSplash := nil;
  end;
  {$IFDEF TESTES}
  ACBrRunTests;
  {$ENDIF}
  Application.Run;
end.

