unit wr.Form;

interface

procedure Inicializa_WR_Form;

const
  //********* Definição da última versão Desse objeto ***********

  Versao_Inicializa_WR_Form = 1;

implementation

Uses
  Base, Tag.APP, Tag.Form;

procedure Inicializa_WR_Form;
begin
  RegisterWR_Form(Tag_Produto_ProdutoSimples, TagAPP_Venda, 'Produto Simples');
  RegisterWR_Form(Tag_Produto_ProdutoSimples, TagAPP_Codigo_Barras, 'Produto Simples');
  RegisterWR_Form(Tag_Produto_ProdutoSimples, TagAPP_Estoque, 'Produto Simples');
  RegisterWR_Form(Tag_Produto_Venda, TagAPP_Estoque, 'Produtos para Venda');
  RegisterWR_Form(Tag_Produto_Servico, TagAPP_Produto_Servico, 'Serviços');
  RegisterWR_Form(Tag_Produto_Variacao, TagAPP_Produto_Variacao, 'Produto com Variação');
  RegisterWR_Form(Tag_Produto_Composicao, TagAPP_Produto_Composicao, 'Produto com Composição');
  RegisterWR_Form(Tag_Produto_MateriaPrima, TagAPP_Produto_MateriaPrima, 'Matéria Prima');
  RegisterWR_Form(Tag_Produto_Personalizado, TagAPP_Produto_Personalizado, 'Produto Personalizados');
  RegisterWR_Form(Tag_Produto_Patrimonio, TagAPP_Produto_Patrimonio, 'Patrimônio');
  RegisterWR_Form(Tag_Produto_UsoEConsumo, TagAPP_Produto_UsoEConsumo, 'Produto de Uso e Consumo');
  RegisterWR_Form(Tag_Produto_Lote, TagAPP_Lote, 'Lote de Produto');
  RegisterWR_Form(Tag_Estoque_Local, TagAPP_Multiplos_Estoques, 'Local de Estoque');
  RegisterWR_Form(Tag_SPED, TagAPP_Integracao_SPED, 'SPED');
  RegisterWR_Form(Tag_Sintegra, TagAPP_Integracao_Sintegra, 'Sintegra');
  RegisterWR_Form(Tag_Agenda, TagAPP_Agendamentos, 'Agendamentos');
  RegisterWR_Form(Tag_Tipo_Agenda, TagAPP_Agendamentos, 'Tipo de Agenda');
  RegisterWR_Form(Tag_Email_Massa, TagAPP_Email_Massa, 'Email em Massa');
  RegisterWR_Form(Tag_Tipo_Venda, TagAPP_Venda, 'Tipos de Venda');
  RegisterWR_Form(Tag_Venda, TagAPP_Venda, 'Venda');
  RegisterWR_Form(Tag_Venda_Projeto, TagAPP_Venda, 'Venda Projeto');
  RegisterWR_Form(Tag_ImpriVendas_Periodo, TagAPP_Venda, 'Relatório de Venda');
  RegisterWR_Form(Tag_Situacao_Venda, TagAPP_Venda, 'Situação de Venda');
  RegisterWR_Form(Tag_Venda_PDV, TagAPP_Venda_PDV, 'PDV');
  RegisterWR_Form(Tag_Venda_Pedido, TagAPP_Venda_Pedido, 'Pedido');
  RegisterWR_Form(Tag_Producao, TagAPP_Ordem_Producao, 'Produção');
  RegisterWR_Form(Tag_Producao_Relatorio, TagAPP_Ordem_Producao, 'Relatório de Produção');
  RegisterWR_Form(Tag_Producao_Equipe, TagAPP_Ordem_Producao, 'Equipe de Produção');
  RegisterWR_Form(Tag_Producao_Setor, TagAPP_Ordem_Producao, 'Setor de Produção');
  RegisterWR_Form(Tag_Producao_Local_Aplicacao, TagAPP_Ordem_Producao, 'Local de Aplicação');
  RegisterWR_Form(Tag_Producao_Tipo_Impressao, TagAPP_Ordem_Producao, 'Local de Aplicação');
  RegisterWR_Form(Tag_Producao_Acabamento, TagAPP_Ordem_Producao, 'Acabamento');
  RegisterWR_Form(Tag_Notificacoes, TagAPP_Notificacoes, 'Notificação');
  RegisterWR_Form(Tag_Ficha_Ponto, TagAPP_RH_Ficha_Ponto, 'Acabamento');
  RegisterWR_Form(Tag_Producao_Projeto, TagAPP_Projeto, 'Projeto');
  RegisterWR_Form(Tag_Venda_Metas, TagAPP_Venda_Metas, 'Metas de Venda');
  RegisterWR_Form(Tag_Comissao, TagAPP_Venda_Comissoes, 'Comissão de Venda');
  RegisterWR_Form(Tag_Financeiro, TagAPP_Financeiro, 'Financeiro');
  RegisterWR_Form(Tag_Financeiro_A_Pagar, TagAPP_Financeiro, 'Financeiro a Pagar');
//  Register_Tela(TagAPP_Financeiro, TagAPP_Financeiro);
  RegisterWR_Form(Tag_Notas_Fiscais, TagAPP_NFe, 'Nota Fiscal');
  RegisterWR_Form(Tag_Notas_Fiscais, TagAPP_NFSe, 'Nota Fiscal');
  RegisterWR_Form(Tag_Compra, TagAPP_Compra, 'Compra');
  RegisterWR_Form(Tag_Boleto, TagAPP_Financeiro_Boleto, 'Boleto');
  RegisterWR_Form(Tag_Boleto_API, TagAPP_Financeiro_Boleto, 'Boleto API');
  RegisterWR_Form(Tag_Cheque, TagAPP_Financeiro_Cheque, 'Cheque');
  RegisterWR_Form(Tag_Conciliacao_bancaria, TagAPP_Financeiro_Conciliacao_Bancaria, 'Conciliação Bancária');
  RegisterWR_Form(Tag_Codigo_Barras, TagAPP_Codigo_Barras, 'Código de Barras');
  RegisterWR_Form(Tag_Balanco, TagAPP_Estoque, 'Balanço');
  RegisterWR_Form(Tag_Estoque_Produto_Movimento, TagAPP_Estoque, 'Produto Movimento');
  RegisterWR_Form(Tag_Estoque_Local, TagAPP_Estoque, 'Local de Estoque');
  RegisterWR_Form(Tag_DRE, TagAPP_DRE, 'DRE');
  RegisterWR_Form(Tag_DRE_Classificacao, TagAPP_DRE, 'Classificação de DRE');
  RegisterWR_Form(Tag_Contrato, TagAPP_Financeiro_Contrato, 'Contrato');
  RegisterWR_Form(Tag_Caixa, TagAPP_Financeiro_Caixa, 'Caixa');
  RegisterWR_Form(Tag_Recebimento, TagAPP_Financeiro_Caixa, 'Recebimento');
  RegisterWR_Form(Tag_Financeiro_Centro_Custo_Produto_Categoria, TagAPP_Financeiro_Centro_Custo, 'Centro de Custo Produto Categoria');
  RegisterWR_Form(Tag_Folha_Pagamento, TagAPP_RH_Folha_Pagamento, 'Folha de Pagamento');
  RegisterWR_Form(Tag_Folha_Pagamento_Grupo, TagAPP_RH_Folha_Pagamento, 'Grupo de Folha de Pagamento');
  RegisterWR_Form(Tag_Setores, TagAPP_RH_Folha_Pagamento, 'Setores RH');
  RegisterWR_Form(Tag_Pessoas_Funcionario, TagAPP_RH_Funcionarios, 'Funcionários');
  RegisterWR_Form(Tag_Venda_Orcamento, TagAPP_Propostas, 'Orçamentos');
  RegisterWR_Form(Tag_Arquivos_Relatorio, TagAPP_Relatorio, 'Relatórios');
  RegisterWR_Form(Tag_Equipamento_Associacao, TagAPP_Equipamento_Associacao, 'Equipamentos Associação');
  RegisterWR_Form(Tag_Rateio, TagAPP_Rateio, 'Rateio');
  RegisterWR_Form(Tag_Tabela_Fipe, TagAPP_Equipamento_Associacao, 'Tabela FIPE');
  RegisterWR_Form(Tag_Tabela_Valor, TagAPP_Equipamento_Associacao, 'Tabela Valor');
  RegisterWR_Form(Tag_Tipo_Equipamento, TagAPP_Equipamento_Associacao, 'Tipo de Equipamento');
  RegisterWR_Form(Tag_Situacao, TagAPP_Equipamento_Associacao, 'Situação Equipamento');
  RegisterWR_Form(Tag_Mala_Direta, TagAPP_Equipamento_Associacao, 'Mala Direta');
  RegisterWR_Form(Tag_Rel_Associados, TagAPP_Associacao, 'Relação Associados');
  RegisterWR_Form(Tag_Ocorrencias, TagAPP_Ocorrencias, 'Ocorrências');
  RegisterWR_Form(Tag_Ocorrencias_Tipo, TagAPP_Ocorrencias, 'Tipos de Ocorrência');
  RegisterWR_Form(Tag_Rel_Ocorrencias, TagAPP_Ocorrencias, 'Relação de Ocorrências');
  RegisterWR_Form(Tag_Producao_Planejamento, TagAPP_Planejamento, 'Planejamento');
  RegisterWR_Form(Tag_Producao_Fila_TV, TagAPP_Producao_Fila_TV, 'Produção - Fila TV');
  RegisterWR_Form(Tag_Produto_Grade_Modelo, TagAPP_Produto_Variacao, 'Modelo de Grade');
  RegisterWR_Form(Tag_Produto_Familia, TagAPP_Produto_Variacao, 'Família de Produto');
  RegisterWR_Form(Tag_Markup, TagAPP_Markup, 'Markup');
  RegisterWR_Form(Tag_Tabela_Preco, TagAPP_Venda_Tabela_Preço, 'Tabela de Preço');
  RegisterWR_Form(Tag_Producao_Roteiro, TagAPP_Produto_Personalizado, 'Roteiro de Produção');
  RegisterWR_Form(Tag_NFSe_Provedor, TagAPP_NFSe, 'Provedor NFSe');
  RegisterWR_Form(Tag_Funcionario_Ficha_Ponto, TagAPP_RH_Ficha_Ponto, 'Ficha Ponto do Funcionário');
  RegisterWR_Form(Tag_Manifestacao_NotaFiscalEntrada, TagAPP_Importacao_Xml, 'Manifestação do Destinatário');
  RegisterWR_Form(Tag_Pessoas, TagAPP_Geral, 'Pessoas');
  RegisterWR_Form(Tag_Pessoas_Fornecedor, TagAPP_Geral, 'Pessoas Fornecedor');
  RegisterWR_Form(Tag_Pessoas_Grupo, TagAPP_Geral, 'Grupo de Pessoas');
  RegisterWR_Form(Tag_Pessoas_OImpresso, TagAPP_Integracao_OImpresso, 'Integração - Pessoas OImpresso');     // Esse aqui tem que integrar com o APP do Office Impresso
  RegisterWR_Form(Tag_Pessoas_Representante, TagAPP_Geral, 'Pessoas Representante');
  RegisterWR_Form(Tag_Pessoas_Cliente, TagAPP_Geral, 'Pessoas Cliente');
  RegisterWR_Form(Tag_Pessoas_Todos, TagAPP_Geral, 'Pessoas Todos');
  RegisterWR_Form(Tag_Pessoas_Associado, TagAPP_Associacao, 'Pessoas Associado');
// --------------TAGS QUE FALTAM REGISTRAR------------ //
//  Tag_NF_Entrada_Produto = 11;
//  Tag_RelVenda_Produto = 12;
//  Tag_Estoque_Estoque = 14;
//  Tag_Estoque_Requisicao = 15;
//  Tag_Estoque_Requisicao_Motivo = 16;
//  Tag_Venda_produto = 17;
//  Tag_API_Oimpresso_Pessoas = 18;
//  Tag_API_Oimpresso_Configuracao = 19;
//  Tag_API_Oimpresso = 20;
//  Tag_Boleto_Log = 22;
//  Tag_Credito = 23;
//  Tag_ProdutoSubUnidade = 24;
//  Tag_Conciliacao_bancaria_Arquivos = 32;
//  Tag_Pessoas = 34;
//  Tag_Pessoas_Cliente = 35;
//  Tag_Pessoas_Fornecedor = 36;
//  Tag_Pessoas_Representante = 38;
//  Tag_Pessoas_OImpresso = 39;
//  Tag_Venda_NotaFiscal = 44;
//  Tag_Venda_OImpresso = 45;
//  Tag_Manifestacao_HistoricoRequisicoes = 49;
//  Tag_Manifestacao_Detalhes = 50;
//  Tag_Pessoas_Associado = 53;
//  Tag_Antifurto_Tipo = 57;
//  Tag_Equipamento_Veiculo = 59;
//  Tag_Equipamento_Computador = 60;
//  Tag_Equipamento_Impressora = 61;
//  Tag_Equipamento_Eletrodomestico = 62;
//  Tag_Comissao_Selecao_Financeiro = 63;
//  Tag_Comissao_Selecao_Venda = 64;
//  Tag_Comissao_Selecao_Financeiro_Representante = 65;
//  Tag_Comissao_Selecao_Financeiro_Agencia = 66;
//  Tag_Comissao_Selecao_Financeiro_Funcionario = 67;
//  Tag_Cor = 68;
//  Tag_Mensagens = 69;
//  Tag_BI = 70;
//  Tag_BI_KPI = 71;
//  Tag_BI_Configuracoes = 73;
//  Tag_BI_Vendas = 74;
//  Tag_BI_Financeiro = 75;
//  Tag_BI_Producao = 76;
//  Tag_BI_Estoque = 77;
//  Tag_BI_Compras = 78;
//  Tag_BI_Venda_por_Funcionario = 79;
//  Tag_BI_Venda_Por_Produto_Tipo = 80;
//  Tag_APP = 81;
//  Tag_BI_Venda_por_Categoria = 82;
//  Tag_BI_Estoque_Produto_Movimento = 83;
//  Tag_BI_Empresa = 84;
//  Tag_BI_Faturamento = 85;
//  Tag_BI_Associacao = 86;
//  Tag_BI_RH = 87;
//  Tag_Notificacao_Disparada = 101;
//  Tag_Configuracao_Cronjob = 102;
//  Tag_API_Oimpresso_Produtos = 104;
//  Tag_Configuracao = 105;
//  Tag_BI_Venda = 107;
//  Tag_BI_Acoes = 108;
//  Tag_BI_Permissoes = 109;
//  Tag_Financeiro_A_Receber = 136;
//  Tag_Plano_Contas = 166;
//  Tag_ImpriProdutos_Gerencial = 167;
//  Tag_Notas_Fiscal_Servico = 168;
//  Tag_ImpriEntradas = 169;
//  Tag_Recibo = 170;
//  Tag_ImpriAgenda = 171;
//  Tag_ImpriProducao = 172;
//  Tag_ImpriClientes_Ativos = 173;
//  Tag_Funcionario_Ficha_Ponto = 174;
//  Tag_ConDRE = 175;
//  Tag_Produto_Tipo = 176;
//  Tag_Produto_Categoria = 177;
//  Tag_Produto_Grupo = 178;
//  Tag_Produto_Unidade = 179;
//  Tag_Produto_Marca = 180;
//  Tag_Produto_Relatorio_PautaPreco = 181;
//  Tag_Produto_Relatorio_Gerencial = 182;
//  Tag_Produto_Relatorio_Patrimonial = 183;
//  Tag_Pessoas_Telefone = 184;
//  Tag_Pessoas_Grupo = 185;
//  Tag_Pessoas_Relatorio = 186;
//  Tag_pessoas_tipo = 187;
//  Tag_Cidades = 188;
//  Tag_Producao_Marcador = 189;
//  Tag_Producao_Motivo = 190;
//  Tag_Producao_Situacao = 191;
//  Tag_Venda_Estagio = 192;
//  Tag_Venda_BI_Categoria = 194;
//  Tag_Venda_BI_Funcionario = 195;
//  Tag_Venda_BI_TipoProduto = 196;
//  Tag_Venda_Relatorio = 197;
//  Tag_NotaFiscal_NatOp = 198;
//  Tag_NotaFiscal_CEST = 199;
//  Tag_NotaFiscal_CFOP = 200;
//  Tag_NotaFiscal_NCM = 201;
//  Tag_NotaFiscal_CST = 202;
//  Tag_NotaFiscal_CNAE = 203;
//  Tag_NotaFiscal_Provedor = 204;
//  Tag_Email_Modelo = 206;
//  Tag_Almoxarifado = 207;
//  Tag_LogOff = 211;
//  Tag_Trocar_Senha = 212;
//  Tag_Usuario = 213;
//  Tag_Empresa = 214;
//  Tag_Apps = 215;
//  Tag_Empresa_Ativa = 216;
//  Tag_Financeiro_TipoPagamento = 217;
//  Tag_Financeiro_CaixaConta = 218;
//  Tag_Cadastro_Banco = 219;
//  Tag_BoletosEventuais = 222;
//  Tag_Agenda_Producao = 223;
//  Tag_Agenda_Kanban = 224;
//  Tag_Balanco_Patrimonial_Classificacao = 225;
//  Tag_Balanco_Patrimonial = 226;
//  Tag_DFC = 227;
//  Tag_DFC_Classificacao = 228;
//  Tag_BI_Geral = 229;
//  Tag_BI_Gerencia = 230;
//  Tag_Salario = 231;
//  Tag_Precificacao = 232;
//  Tag_Producao_Rateio = 233;

// --- TAGS COMENTADAS --- //
//  Tag_Ocorrencia_Tipo = 51;  /// Não existe olha na 154
//  Tag_BI = 72;
//  Tag_Painel_BI = 106;
end;

initialization
  Inicializa_WR_Form;

end.
